### ISSUE TITLE
[SQL] Numeric Literal out of range for Decimal types

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1154]
To reproduce, create a new test and extend `SqlIoTest`. 

Override `prepareData` as follows: 
```java
    @Override
    public void prepareData(DBSPCompiler compiler) {
        String createTables = "create table wl1612 (col1 int, col2 decimal(38,10), col3 numeric(38,10));";

        String insert = "insert into wl1612 values(1,12345678901234567890.1234567890,12345678901234567890.1234567890);\n";

        compiler.compileStatements(createTables);
        compiler.compileStatements(insert);
    }
```

And then just add any test function as the error occurs when we are inserting into the table. 

Test taken from: https://github.com/mysql/mysql-server/blob/87307d4ddd88405117e3f1e51323836d57ab1f57/mysql-test/t/type_newdecimal.test#L111

Stack trace: 
```java
(no input file): Error in SQL statement
(no input file):8:29: error: Error in SQL statement: Numeric literal '12345678901234567890.1234567890' out of range
    8|insert into wl1612 values(1,12345678901234567890.1234567890,12345678901234567890.1234567890);
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


java.lang.RuntimeException: org.apache.calcite.runtime.CalciteContextException: From line 8, column 29 to line 8, column 59: Numeric literal '12345678901234567890.1234567890' out of range

	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:291)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatements(DBSPCompiler.java:328)
	at org.dbsp.sqlCompiler.compiler.sql.simple.DecimalCastTests.prepareData(DecimalCastTests.java:23)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.compare(SqlIoTest.java:529)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.q(SqlIoTest.java:556)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:607)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:615)
	at org.dbsp.sqlCompiler.compiler.sql.simple.DecimalCastTests.selectCount(DecimalCastTests.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 8, column 29 to line 8, column 59: Numeric literal '12345678901234567890.1234567890' out of range
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:507)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:948)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:933)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5517)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateLiteral(SqlValidatorImpl.java:3327)
	at org.apache.calcite.sql.SqlLiteral.validate(SqlLiteral.java:578)
	at org.apache.calcite.sql.SqlNode.validateExpr(SqlNode.java:275)
	at org.apache.calcite.sql.SqlOperator.validateCall(SqlOperator.java:475)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateCall(SqlValidatorImpl.java:6232)
	at org.apache.calcite.sql.SqlCall.validate(SqlCall.java:143)
	at org.apache.calcite.sql.SqlNode.validateExpr(SqlNode.java:275)
	at org.apache.calcite.sql.SqlOperator.validateCall(SqlOperator.java:475)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateCall(SqlValidatorImpl.java:6232)
	at org.apache.calcite.sql.SqlCall.validate(SqlCall.java:143)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1091)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:797)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:607)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:886)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:264)
	... 36 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Numeric literal '12345678901234567890.1234567890' out of range
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:507)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:601)
	... 54 more


Process finished with exit code 255

```

**Comment by mihaibudiu** [comment]
Another Calcite bug, which has been open since 2019: https://issues.apache.org/jira/browse/CALCITE-3522

**Comment by mihaibudiu** [comment]
Fix available in https://github.com/apache/calcite/pull/3589
