### ISSUE TITLE
[SQL] Incorrect Decimal Casts

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1155]
The following test fails right now, meaning that decimal casts don't quite work. 
```java
    @Test
    public void simpleCast() {
        this.q("SELECT 2.451::DECIMAL(3, 2) as decimal;\n" +
                " decimal \n" +
                "---------\n" +
                " 2.45"
        );
    }
```

Failure: 
```rust
error: test failed, to rerun pass `--lib`
stdout ----
R: (2.45,)x1
L: (2.451,)x1
thread 'test0' panicked at src/lib.rs:112:5:

    mvn test -Dtest=DecimalCastTests#simpleCast
    SELECT 2.451::DECIMAL(3, 2) as decimal

---- test1 stdout ----
R: (2.45,)x1
L: (2.451,)x1
thread 'test1' panicked at src/lib.rs:148:5:

    mvn test -Dtest=DecimalCastTests#simpleCast
    SELECT 2.451::DECIMAL(3, 2) as decimal
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test0
    test1

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Similarly: 

```java
    @Test
    public void testAddition() {
        this.qs(
                "SELECT 2.451::DECIMAL(3, 2) + 3.1::DECIMAL(2, 1) as sum;\n" +
                        " sum \n" +
                        "-----\n" +
                        " 5.55\n" +
                        "(1 row)\n" +
                        "\n"
        );
    }
```
The above test generates the following code: 

Optimized by Calcite: (fails) ❌
```rust
        let stream1: Stream<_, OrdZSet<Tuple1<Decimal>, Weight>> = stream0.map(move |t: &Tuple1<i32>, | -> 
        Tuple1<Decimal> {
            Tuple1::new(Decimal::from_str("5.551").unwrap())
        });
```

Calculated in run time: (passes) ✅
```rust
        let stream3: Stream<_, OrdZSet<Tuple1<Decimal>, Weight>> = stream2.map(move |t: &Tuple1<i32>, | -> 
        Tuple1<Decimal> {
            Tuple1::new(cast_to_decimal_decimal(plus_decimal_decimal(Decimal::from_str("2.451").unwrap(), cast_to_decimal_decimal(Decimal::from_str("3.1").unwrap(), 3, 2)), 4, 2))
        });
```

Both test queries produce the correct result in Postgres.

**Comment by mihaibudiu** [comment]
@abhizer I can't reproduce any of these two problems.
It looks like they were actually fixed by your commits that handle casting for decimal values.
Can you double check and close the issue that's right?

**Comment by abhizer** [comment]
Yup, these tests pass. Probably as a result of #1300. 

Closing as completed.
