### ISSUE TITLE
[SQL] Internal Compiler Error: Overflow

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1199]
The test that causes it: 
```java
    @Test
    public void ICEOverflow() {
        this.runtimeFail("SELECT CAST('922337203685477580700.0'::float8 AS int64)", "Overflow", this.getEmptyIOPair());
    }
```

Stack trace: 
```java
error: This is a bug in the compiler (please report it to the developers): Overflow


java.lang.ArithmeticException: Overflow

	at java.base/java.math.BigDecimal.longValueExact(BigDecimal.java:3650)
	at org.apache.calcite.linq4j.tree.Primitive.numberValue(Primitive.java:425)
	at org.apache.calcite.linq4j.tree.Expressions.constant(Expressions.java:575)
	at org.apache.calcite.linq4j.tree.OptimizeShuttle.visit(OptimizeShuttle.java:301)
	at org.apache.calcite.linq4j.tree.UnaryExpression.accept(UnaryExpression.java:39)
	at org.apache.calcite.linq4j.tree.TernaryExpression.accept(TernaryExpression.java:47)
	at org.apache.calcite.linq4j.tree.Expressions.acceptExpressions(Expressions.java:3214)
	at org.apache.calcite.linq4j.tree.NewArrayExpression.accept(NewArrayExpression.java:49)
	at org.apache.calcite.linq4j.tree.GotoStatement.accept(GotoStatement.java:64)
	at org.apache.calcite.linq4j.tree.BlockBuilder.optimize(BlockBuilder.java:455)
	at org.apache.calcite.linq4j.tree.BlockBuilder.toBlock(BlockBuilder.java:340)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:102)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:68)
	at org.apache.calcite.rex.RexExecutorImpl.reduce(RexExecutorImpl.java:133)
	at org.apache.calcite.rex.RexSimplify.simplifyCast(RexSimplify.java:2265)
	at org.apache.calcite.rex.RexSimplify.simplify(RexSimplify.java:292)
	at org.apache.calcite.rex.RexSimplify.simplifyUnknownAs(RexSimplify.java:250)
	at org.apache.calcite.rex.RexSimplify.simplifyPreservingType(RexSimplify.java:189)
	at org.apache.calcite.rex.RexSimplify.simplifyPreservingType(RexSimplify.java:184)
	at org.apache.calcite.tools.RelBuilder.lambda$project_$7(RelBuilder.java:2049)
	at java.base/java.util.ArrayList.replaceAllRange(ArrayList.java:1795)
	at java.base/java.util.ArrayList.replaceAll(ArrayList.java:1785)
	at org.apache.calcite.tools.RelBuilder.project_(RelBuilder.java:2049)
	at org.apache.calcite.tools.RelBuilder.project(RelBuilder.java:1900)
	at org.apache.calcite.tools.RelBuilder.projectNamed(RelBuilder.java:2233)
	at org.apache.calcite.tools.RelBuilder.projectNamed(RelBuilder.java:2170)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectList(SqlToRelConverter.java:4599)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:769)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:690)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3769)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:610)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:874)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:264)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:320)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:340)
	at org.dbsp.sqlCompiler.compiler.sql.BaseSQLTests.runtimeFail(BaseSQLTests.java:196)
	at org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresInt8Tests.testOutOfRangeCast(PostgresInt8Tests.java:553)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


Process finished with exit code 255
```

**Comment by mihaibudiu** [comment]
This is a Calcite bug, possibly one which I have fixed. We'll check again after my changes are merged.
