### ISSUE TITLE
[SQL]: ICE - Casting to bytea causes bug

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1268]
A test as such: 
```java
    @Test
    public void testSubstring2() {
        this.qs(
                """
                        SELECT '1234567890'::bytea as val;
                         val
                        -----
                         31323334353637383930
                        (1 row)
                        """
        );
    }
```
Causes an internal compiler error. Even if the casting is invalid, it shouldn't be a bug in the compiler. 

Stack trace: 
```java
error: This is a bug in the compiler (please report it to the developers): value 1234567890 does not match type class org.apache.calcite.avatica.util.ByteString


java.lang.AssertionError: value 1234567890 does not match type class org.apache.calcite.avatica.util.ByteString

	at org.apache.calcite.linq4j.tree.ConstantExpression.<init>(ConstantExpression.java:51)
	at org.apache.calcite.linq4j.tree.Expressions.constant(Expressions.java:585)
	at org.apache.calcite.linq4j.tree.OptimizeShuttle.visit(OptimizeShuttle.java:301)
	at org.apache.calcite.linq4j.tree.UnaryExpression.accept(UnaryExpression.java:39)
	at org.apache.calcite.linq4j.tree.TernaryExpression.accept(TernaryExpression.java:47)
	at org.apache.calcite.linq4j.tree.DeclarationStatement.accept(DeclarationStatement.java:45)
	at org.apache.calcite.linq4j.tree.DeclarationStatement.accept(DeclarationStatement.java:27)
	at org.apache.calcite.linq4j.tree.BlockBuilder.optimize(BlockBuilder.java:426)
	at org.apache.calcite.linq4j.tree.BlockBuilder.toBlock(BlockBuilder.java:340)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:102)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:68)
	at org.apache.calcite.rex.RexExecutorImpl.reduce(RexExecutorImpl.java:133)
	at org.apache.calcite.rex.RexSimplify.simplifyCast(RexSimplify.java:2265)
	at org.apache.calcite.rex.RexSimplify.simplify(RexSimplify.java:292)
	at org.apache.calcite.rex.RexSimplify.simplifyUnknownAs(RexSimplify.java:250)
	at org.apache.calcite.rex.RexSimplify.simplifyPreservingType(RexSimplify.java:189)
	at org.apache.calcite.rex.RexSimplify.simplifyPreservingType(RexSimplify.java:184)
	at org.apache.calcite.tools.RelBuilder.lambda$project_$7(RelBuilder.java:2049)
	at java.base/java.util.ArrayList.replaceAllRange(ArrayList.java:1795)
	at java.base/java.util.ArrayList.replaceAll(ArrayList.java:1785)
	at org.apache.calcite.tools.RelBuilder.project_(RelBuilder.java:2049)
	at org.apache.calcite.tools.RelBuilder.project(RelBuilder.java:1900)
	at org.apache.calcite.tools.RelBuilder.projectNamed(RelBuilder.java:2233)
	at org.apache.calcite.tools.RelBuilder.projectNamed(RelBuilder.java:2170)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectList(SqlToRelConverter.java:4599)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:769)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:690)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3769)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:610)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:835)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:264)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:320)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:340)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.compare(SqlIoTest.java:522)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.q(SqlIoTest.java:548)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:615)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:623)
	at org.dbsp.sqlCompiler.compiler.sql.mysql.VarbinaryTests.testSubstring2(VarbinaryTests.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


Process finished with exit code 255

```

**Comment by mihaibudiu** [comment]
This is a true bug I filed for Calcite: https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-6210

**Comment by mihaibudiu** [comment]
Fix available in Calcite https://github.com/apache/calcite/pull/3635 not yet merged
