### ISSUE TITLE
[SQL] ICE: Casting invalid value to REAL causes compiler bug

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1345]
This produces a compiler bug. 

Even casting an invalid value to real produces a compiler bug. Consider a test as such: 
```java
    @Test
    public void testIsInfReal() {
        this.qs("""
                -- f64::MAX
                SELECT 1.7976931348623157e308::real;
                real
                -------
                 1.79
                (1 row)
                
                -- f64::MIN
                SELECT -1.7976931348623157e308::real;
                real
                -------
                 -1.79
                (1 row)
                """
        );
    }

```

Causes:

```java
error: This is a bug in the compiler (please report it to the developers): Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.


java.lang.NumberFormatException: Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:594)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:483)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:889)
	at java.base/java.math.BigDecimal.valueOf(BigDecimal.java:1357)
	at org.apache.calcite.linq4j.tree.ConstantExpression.write(ConstantExpression.java:109)
	at org.apache.calcite.linq4j.tree.ConstantExpression.accept(ConstantExpression.java:77)
	at org.apache.calcite.linq4j.tree.UnaryExpression.accept(UnaryExpression.java:62)
	at org.apache.calcite.linq4j.tree.ExpressionWriter.list(ExpressionWriter.java:167)
	at org.apache.calcite.linq4j.tree.NewArrayExpression.accept(NewArrayExpression.java:71)
	at org.apache.calcite.linq4j.tree.GotoStatement.accept0(GotoStatement.java:88)
	at org.apache.calcite.linq4j.tree.Statement.accept(Statement.java:32)
	at org.apache.calcite.linq4j.tree.BlockStatement.accept0(BlockStatement.java:78)
	at org.apache.calcite.linq4j.tree.ExpressionWriter.append(ExpressionWriter.java:131)
	at org.apache.calcite.linq4j.tree.MethodDeclaration.accept(MethodDeclaration.java:75)
	at org.apache.calcite.linq4j.tree.ExpressionWriter.write(ExpressionWriter.java:51)
	at org.apache.calcite.linq4j.tree.Expressions.toString(Expressions.java:61)
	at org.apache.calcite.linq4j.tree.Expressions.toString(Expressions.java:71)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:103)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:68)
	at org.apache.calcite.rex.RexExecutorImpl.reduce(RexExecutorImpl.java:133)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressionsInternal(ReduceExpressionsRule.java:774)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressions(ReduceExpressionsRule.java:714)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:313)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337)
	at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556)
	at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:420)
	at org.apache.calcite.plan.hep.HepPlanner.executeRuleInstance(HepPlanner.java:243)
	at org.apache.calcite.plan.hep.HepInstruction$RuleInstance$State.execute(HepInstruction.java:178)
	at org.apache.calcite.plan.hep.HepPlanner.lambda$executeProgram$0(HepPlanner.java:211)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:210)
	at org.apache.calcite.plan.hep.HepProgram$State.execute(HepProgram.java:118)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:205)
	at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:191)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.optimize(CalciteCompiler.java:542)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:838)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:264)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:320)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:340)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.compare(SqlIoTest.java:521)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.q(SqlIoTest.java:547)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:614)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:622)
	at org.dbsp.sqlCompiler.compiler.sql.functions.FunctionsTest.testIsInfReal(FunctionsTest.java:425)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


```

_Originally posted by @abhizer in https://github.com/feldera/feldera/pull/1344#discussion_r1468076443_

**Comment by abhizer** [comment]
Fixed by: https://issues.apache.org/jira/browse/CALCITE-6094
Just not released yet.

**Comment by mihaibudiu** [comment]
Calcite PR with fix: https://github.com/apache/calcite/pull/3511
