### ISSUE TITLE
playwright test failures

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1429]
```
+test-docker-compose-stable | Untagged: 172.30.0.1:8371/sess-4fz8e0w2v0bmfb3h0nmh4mz2r:img-3
+test-docker-compose-stable | Untagged: 172.30.0.1:xxxxx@sha256:4a5caf8065ca7f78eeb5a97012503ac7d62f18eb5f40b9942e113806158387ea
+ui-playwright-tests | 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-0
+ui-playwright-tests | Untagged: 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-0
+ui-playwright-tests | Untagged: 172.30.0.1:xxxxx@sha256:de84a0ea622daa90d22330fe58cbc0ead4d155282aed55c998ff9a756a58ec39
+ui-playwright-tests | Loading images done in 209093 ms
+ui-playwright-tests |  Network default_default  Creating
+ui-playwright-tests |  Network default_default  Created
+ui-playwright-tests |  Container default-db-1  Creating
+ui-playwright-tests |  Container default-db-1  Created
+ui-playwright-tests |  Container default-pipeline-manager-1  Creating
+ui-playwright-tests |  Container default-pipeline-manager-1  Created
+ui-playwright-tests |  Container default-db-1  Starting
+ui-playwright-tests |  Container default-db-1  Started
+ui-playwright-tests |  Container default-db-1  Waiting
+ui-playwright-tests |  Container default-db-1  Healthy
+ui-playwright-tests |  Container default-pipeline-manager-1  Starting
+ui-playwright-tests |  Container default-pipeline-manager-1  Started
+ui-playwright-tests | yarn run v1.22.21
+ui-playwright-tests | $ /dbsp/node_modules/.bin/playwright test
+test-docker-compose | 172.30.0.1:8371/sess-410za180jpbebvydmds9sokwr:img-1
     +test-snowflake | 172.30.0.1:8371/sess-s5v0f6vghva8sbn7g8lrqt2jl:img-1
+test-docker-compose | Untagged: 172.30.0.1:8371/sess-410za180jpbebvydmds9sokwr:img-1
+test-docker-compose | Untagged: 172.30.0.1:xxxxx@sha256:978828f31aca549657890a1c316ad89315a4b1601c77a4f2fd4ebb1d2d7961f7
     +test-snowflake | Untagged: 172.30.0.1:8371/sess-s5v0f6vghva8sbn7g8lrqt2jl:img-1
     +test-snowflake | Untagged: 172.30.0.1:xxxxx@sha256:978828f31aca549657890a1c316ad89315a4b1601c77a4f2fd4ebb1d2d7961f7

+ui-playwright-tests | Running 5 tests using 1 worker
+ui-playwright-tests | F


+ui-playwright-tests |   1) [setup] › global.setup.ts:21:6 › Global prepare ───────────────────────────────────────────────

+ui-playwright-tests |     Error: page.goto: net::ERR_SOCKET_NOT_CONNECTED at http://localhost:8080/
+ui-playwright-tests |     Call log:
+ui-playwright-tests |       - navigating to "http://localhost:8080/", waiting until "load"


+ui-playwright-tests |       20 |
+ui-playwright-tests |       21 | setup('Global prepare', async ({ page }) => {
+ui-playwright-tests |     > 22 |   await page.goto(appOrigin)
+ui-playwright-tests |          |              ^
+ui-playwright-tests |       23 |
+ui-playwright-tests |       24 |   await setup.step('Prepare: Delete pipelines', async () => {
+ui-playwright-tests |       25 |     await page.getByTestId('button-vertical-nav-pipelines').click()

+ui-playwright-tests |         at /dbsp/tests/global.setup.ts:22:14

+ui-playwright-tests |   1 failed
+ui-playwright-tests |     [setup] › global.setup.ts:21:6 › Global prepare ────────────────────────────────────────────────
+ui-playwright-tests |   4 did not run
+ui-playwright-tests | error Command failed with exit code 1.
+ui-playwright-tests | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
+ui-playwright-tests |   adding: playwright-report/ (stored 0%)
+ui-playwright-tests |   adding: playwright-report/index.html
+ui-playwright-tests |   adding: playwright-report/index.html (deflated 57%)
+ui-playwright-tests |   adding: test-results/ (stored 0%)
+ui-playwright-tests |  Container default-pipeline-manager-1  Stopping
+ui-playwright-tests |  Container default-pipeline-manager-1  Stopped
+ui-playwright-tests |  Container default-pipeline-manager-1  Removing
+ui-playwright-tests |  Container default-pipeline-manager-1  Removed
+ui-playwright-tests |  Container default-db-1  Stopping
+test-debezium-jdbc-sink | 172.30.0.1:8371/sess-p3w9l2hklpn4wk6s470lmpg6t:img-1
+test-debezium-jdbc-sink | Untagged: 172.30.0.1:8371/sess-p3w9l2hklpn4wk6s470lmpg6t:img-1
+test-debezium-jdbc-sink | Untagged: 172.30.0.1:xxxxx@sha256:978828f31aca549657890a1c316ad89315a4b1601c77a4f2fd4ebb1d2d7961f7
+ui-playwright-tests |  Container default-db-1  Stopped
+ui-playwright-tests |  Container default-db-1  Removing
+ui-playwright-tests |  Container default-db-1  Removed
+ui-playwright-tests |  Network default_default  Removing
+ui-playwright-tests |  Network default_default  Removed
+test-docker-compose | 172.30.0.1:8371/sess-410za180jpbebvydmds9sokwr:img-0
+test-docker-compose | Untagged: 172.30.0.1:8371/sess-410za180jpbebvydmds9sokwr:img-0
+test-docker-compose | Untagged: 172.30.0.1:xxxxx@sha256:52ce5e04db4e8ef3a1295a1ea5c8a6bfa8bbb16cda53632bfd6463d2b8c2d3cf
+test-docker-compose | Loading images done in 271 ms
+test-docker-compose |  Network feldera_default  Creating
+test-docker-compose |  Network feldera_default  Created
+test-docker-compose |  Container feldera-redpanda-1  Creating
+test-docker-compose |  Container feldera-db-1  Creating
+ui-playwright-tests | ERROR Earthfile line 471:12
+ui-playwright-tests |       The command
+ui-playwright-tests |           WITH DOCKER RUN --privileged if yarn playwright test; then exit_code=0; else exit_code=$?; fi && cd /dbsp && zip -r playwright-report.zip playwright-report && zip -r test-results.zip test-results && exit $exit_code
+ui-playwright-tests |       did not complete successfully. Exit code 1

================================== ❌ FAILURE ===================================

+ui-playwright-tests *failed* | Repeating the failure error...
+ui-playwright-tests *failed* | PLAYWRIGHT_SNAPSHOTS_COMMIT=2dbb94ea94f32c4f8ea89ce614da262a796b7eed
+ui-playwright-tests *failed* | --> WITH DOCKER RUN --privileged if yarn playwright test; then exit_code=0; else exit_code=$?; fi && cd /dbsp && zip -r playwright-report.zip playwright-report && zip -r test-results.zip test-results && exit $exit_code
+ui-playwright-tests *failed* | Starting dockerd with data root /var/earthly/dind/2ac88b88e33f436a1dcbc7430e53ce0ef8cf03f23df17dcefc1ec3a627a01bc3/tmp.FpXyAexSWB
+ui-playwright-tests *failed* | Loading images from BuildKit via embedded registry...
+ui-playwright-tests *failed* | Pulling 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-0 and retagging as ghcr.io/feldera/pipeline-manager:latest
+ui-playwright-tests *failed* | Pulling 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-2 and retagging as postgres:latest
+ui-playwright-tests *failed* | 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-2
+ui-playwright-tests *failed* | Untagged: 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-2
+ui-playwright-tests *failed* | Untagged: 172.30.0.1:xxxxx@sha256:889cdb9f01eb000269dd94d881f39ff09d4ab16c0768c4a5ed841d35dae9e851
+ui-playwright-tests *failed* | 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-0
+ui-playwright-tests *failed* | Untagged: 172.30.0.1:8371/sess-ey68kwif9s2an7b6xzilboffj:img-0
+ui-playwright-tests *failed* | Untagged: 172.30.0.1:xxxxx@sha256:de84a0ea622daa90d22330fe58cbc0ead4d155282aed55c998ff9a756a58ec39
+ui-playwright-tests *failed* | Loading images done in 209093 ms
+ui-playwright-tests *failed* |  Network default_default  Creating
+ui-playwright-tests *failed* |  Network default_default  Created
+ui-playwright-tests *failed* |  Container default-db-1  Creating
+ui-playwright-tests *failed* |  Container default-db-1  Created
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Creating
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Created
+ui-playwright-tests *failed* |  Container default-db-1  Starting
+ui-playwright-tests *failed* |  Container default-db-1  Started
+ui-playwright-tests *failed* |  Container default-db-1  Waiting
+ui-playwright-tests *failed* |  Container default-db-1  Healthy
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Starting
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Started
+ui-playwright-tests *failed* | yarn run v1.22.21
+ui-playwright-tests *failed* | $ /dbsp/node_modules/.bin/playwright test

+ui-playwright-tests *failed* | Running 5 tests using 1 worker
+ui-playwright-tests *failed* | F

+ui-playwright-tests *failed* |   1) [setup] › global.setup.ts:21:6 › Global prepare ───────────────────────────────────────────────

+ui-playwright-tests *failed* |     Error: page.goto: net::ERR_SOCKET_NOT_CONNECTED at http://localhost:8080/
+ui-playwright-tests *failed* |     Call log:
+ui-playwright-tests *failed* |       - navigating to "http://localhost:8080/", waiting until "load"


+ui-playwright-tests *failed* |       20 |
+ui-playwright-tests *failed* |       21 | setup('Global prepare', async ({ page }) => {
+ui-playwright-tests *failed* |     > 22 |   await page.goto(appOrigin)
+ui-playwright-tests *failed* |          |              ^
+ui-playwright-tests *failed* |       23 |
+ui-playwright-tests *failed* |       24 |   await setup.step('Prepare: Delete pipelines', async () => {
+ui-playwright-tests *failed* |       25 |     await page.getByTestId('button-vertical-nav-pipelines').click()

+ui-playwright-tests *failed* |         at /dbsp/tests/global.setup.ts:22:14

+ui-playwright-tests *failed* |   1 failed
+ui-playwright-tests *failed* |     [setup] › global.setup.ts:21:6 › Global prepare ────────────────────────────────────────────────
+ui-playwright-tests *failed* |   4 did not run
+ui-playwright-tests *failed* | error Command failed with exit code 1.
+ui-playwright-tests *failed* | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
+ui-playwright-tests *failed* |   adding: playwright-report/ (stored 0%)
+ui-playwright-tests *failed* |   adding: playwright-report/index.html (deflated 57%)
+ui-playwright-tests *failed* |   adding: test-results/ (stored 0%)
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Stopping
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Stopped
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Removing
+ui-playwright-tests *failed* |  Container default-pipeline-manager-1  Removed
+ui-playwright-tests *failed* |  Container default-db-1  Stopping
+ui-playwright-tests *failed* |  Container default-db-1  Stopped
+ui-playwright-tests *failed* |  Container default-db-1  Removing
+ui-playwright-tests *failed* |  Container default-db-1  Removed
+ui-playwright-tests *failed* |  Network default_default  Removing
+ui-playwright-tests *failed* |  Network default_default  Removed
+ui-playwright-tests *failed* | ERROR Earthfile line 471:12
+ui-playwright-tests *failed* |       The command
+ui-playwright-tests *failed* |           WITH DOCKER RUN --privileged if yarn playwright test; then exit_code=0; else exit_code=$?; fi && cd /dbsp && zip -r playwright-report.zip playwright-report && zip -r test-results.zip test-results && exit $exit_code
+ui-playwright-tests *failed* |       did not complete successfully. Exit code 1
```

**Comment by gz** [comment]
I think I fixed this by increasing the timeout on the initial connection. closing for now.
