### ISSUE TITLE
[SQL] functions called on array columns fail to compile

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1430]
Consider a test as such:

```java
    @Override
    public void prepareData(DBSPCompiler compiler) {
        String ddl = "CREATE TABLE ARR_TABLE (VALS INTEGER ARRAY NOT NULL,ID INTEGER NOT NULL)";
        String insert = """
                INSERT INTO ARR_TABLE VALUES
                ('{1, 2, 3}', 6),
                ('{1, 2, 3}', 7)
                """;
        compiler.compileStatement(ddl);
        compiler.compileStatement(insert);
    }

    @Test
    public void testUnnest() {
        this.q("""
                SELECT VAL FROM ARR_TABLE, UNNEST(VALS) AS VAL;
                 val
                -----
                 1
                 2
                 3
                 1
                 2
                 3"""
        );
``` 
It fails to compile because:

```java
java.lang.RuntimeException: Vec<i32> is not an instance of class org.dbsp.sqlCompiler.ir.type.primitive.DBSPTypeBaseType

	at org.dbsp.util.ICastable.to(ICastable.java:47)
	at org.dbsp.sqlCompiler.ir.type.DBSPType.baseTypeWithSuffix(DBSPType.java:162)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:524)
	at org.dbsp.sqlCompiler.ir.expression.DBSPCastExpression.accept(DBSPCastExpression.java:51)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:963)
	at org.dbsp.sqlCompiler.ir.expression.DBSPTupleExpression.accept(DBSPTupleExpression.java:117)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:298)
	at org.dbsp.sqlCompiler.ir.expression.literal.DBSPZSetLiteral.accept(DBSPZSetLiteral.java:142)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:931)
	at org.dbsp.sqlCompiler.ir.expression.DBSPRawTupleExpression.accept(DBSPRawTupleExpression.java:53)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:729)
	at org.dbsp.sqlCompiler.ir.DBSPFunction.accept(DBSPFunction.java:78)
	at org.dbsp.sqlCompiler.ir.statement.DBSPFunctionItem.accept(DBSPFunctionItem.java:31)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:790)
	at org.dbsp.sqlCompiler.ir.expression.DBSPBlockExpression.accept(DBSPBlockExpression.java:51)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:726)
	at org.dbsp.sqlCompiler.ir.DBSPFunction.accept(DBSPFunction.java:78)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.toRustString(ToRustInnerVisitor.java:1169)
	at org.dbsp.sqlCompiler.compiler.backend.rust.RustFileWriter.write(RustFileWriter.java:377)
	at org.dbsp.sqlCompiler.compiler.backend.rust.RustFileWriter.writeAndClose(RustFileWriter.java:388)
	at org.dbsp.sqlCompiler.compiler.sql.BaseSQLTests.runAllTests(BaseSQLTests.java:139)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

```

Adapted from a passing test in: https://github.com/feldera/feldera/blob/90ea05f97da88b406b50856b7b4d7ddc59aef9c8/sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayTests.java#L176

Removing the insert statement, the test compiles.

This is true for `ELEMENT` and `ARRAY_APPEND` implementation in: https://github.com/feldera/feldera/pull/1419

**Comment by mihaibudiu** [comment]
There is no cast from string to array, so the latter is probably a Calcite bug, which should reject the program.
We can do it on our side probably.

**Comment by mihaibudiu** [comment]
The second example is just incorrect SQL, it's not a Calcite bug.

**Comment by mihaibudiu** [comment]
Calcite does not have casts from string to array. We should document that.
