### ISSUE TITLE
[SQL] implement missing array functions

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1437]
- [x] Create array from a subquery (aggregate)
- [x] ARRAY_COMPACT https://github.com/feldera/feldera/pull/1493
- [x] ARRAY_CONCAT 
- [x] ARRAY_CONTAINS https://github.com/feldera/feldera/pull/1499
- [x] ARRAY_DISTINCT https://github.com/feldera/feldera/pull/1515
- [x] ARRAY_EXCEPT 
- [x] ARRAY_INSERT
- [x] ARRAY_INSERSECT 
- [x] ARRAY_MAX https://github.com/feldera/feldera/pull/1492
- [x] ARRAY_MIN https://github.com/feldera/feldera/pull/1492
- [x] ARRAY_POSITION
- [x] ARRAY_REMOVE https://github.com/feldera/feldera/pull/1498
- [x] ARRAY_PREPEND https://github.com/feldera/feldera/pull/1496
- [x] ARRAY_REPEAT https://github.com/feldera/feldera/pull/1497
- [x] ARRAY_REVERSE https://github.com/feldera/feldera/pull/1491
- [x] ARRAY_UNION 
- [x] ARRAYS_OVERLAP https://github.com/feldera/feldera/pull/1570
- [ ] ARRAYS_ZIP (don't think we can support this yet)
- [x] SORT_ARRAY https://github.com/feldera/feldera/pull/1490
- [x] ARRAY_SIZE
- [x] ARRAY_LENGTH

**Comment by abhizer** [comment]
Some of the functions fail to compile when writing tests before implementation: 

```java
    @Test @Ignore("runtime exception while compiling")
    public void testArrayConcat() {
        this.qs("""
                SELECT array_concat(ARRAY [1, 2], ARRAY [3, 4]);
                 array_concat
                --------------
                 {1, 2, 3, 4}
                (1 row)
                """
        );
    }

    @Test @Ignore("Reduced expressions should be different from original expressions")
    public void testArrayUnion() {
        this.qs("""
                SELECT array_union(ARRAY [1, 2, 3], ARRAY [2, 4]);
                 array_union
                -------------
                 {1, 2, 3, 4}
                (1 row)
                """
        );
    }

    @Test @Ignore("Reduced expressions should be different from original expressions")
    public void testArrayExcept() {
        this.qs("""
                SELECT array_except(ARRAY [1, 2], ARRAY [2]);
                 array_except
                --------------
                 {1}
                (1 row)
                """
        );
    }

    @Test @Ignore("Reduced expressions should be different from original expressions")
    public void testArrayIntersect() {
        this.qs("""
                SELECT array_intersect(ARRAY [1, 2], ARRAY [2]);
                 array_intersect
                -----------------
                 {1}
                (1 row)
                """
        );
    }
```

**Comment by abhizer** [comment]
`array_concat` fails with: 

```java
error: This is a bug in the compiler (please report it to the developers): While compiling [ARRAY_CONCAT(ARRAY(1, 2), ARRAY(3, 4))]


java.lang.RuntimeException: While compiling [ARRAY_CONCAT(ARRAY(1, 2), ARRAY(3, 4))]

	at org.apache.calcite.rex.RexExecutable.compile(RexExecutable.java:73)
	at org.apache.calcite.rex.RexExecutable.<init>(RexExecutable.java:53)
	at org.apache.calcite.rex.RexExecutorImpl.reduce(RexExecutorImpl.java:137)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressionsInternal(ReduceExpressionsRule.java:774)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressions(ReduceExpressionsRule.java:714)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:313)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337)
	at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556)
	at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:420)
	at org.apache.calcite.plan.hep.HepPlanner.executeRuleInstance(HepPlanner.java:243)
	at org.apache.calcite.plan.hep.HepInstruction$RuleInstance$State.execute(HepInstruction.java:178)
	at org.apache.calcite.plan.hep.HepPlanner.lambda$executeProgram$0(HepPlanner.java:211)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:210)
	at org.apache.calcite.plan.hep.HepProgram$State.execute(HepProgram.java:118)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:205)
	at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:191)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.optimize(CalciteCompiler.java:562)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:855)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:254)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:310)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:330)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.compare(SqlIoTest.java:145)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.q(SqlIoTest.java:172)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:239)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:247)
	at org.dbsp.sqlCompiler.compiler.sql.simple.ArrayFunctionsTests.testArrayConcat(ArrayFunctionsTests.java:208)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.codehaus.commons.compiler.CompileException: Line 10, Column 5: Assignment conversion not possible from type "java.util.ArrayList" to type "java.lang.Object[]"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:13014)
	at org.codehaus.janino.UnitCompiler.assignmentConversion(UnitCompiler.java:11263)
```

`array_union`, `array_except` and `array_intersect` fail with: 

```java
error: This is a bug in the compiler (please report it to the developers): Reduced expressions should be different from original expressions


java.lang.AssertionError: Reduced expressions should be different from original expressions

	at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:315)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337)
	at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556)
	at org.apache.calcite.plan.hep.HepPlanner.depthFirstApply(HepPlanner.java:371)
	at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:437)
	at org.apache.calcite.plan.hep.HepPlanner.executeRuleInstance(HepPlanner.java:243)
	at org.apache.calcite.plan.hep.HepInstruction$RuleInstance$State.execute(HepInstruction.java:178)
	at org.apache.calcite.plan.hep.HepPlanner.lambda$executeProgram$0(HepPlanner.java:211)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:210)
	at org.apache.calcite.plan.hep.HepProgram$State.execute(HepProgram.java:118)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:205)
	at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:191)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.optimize(CalciteCompiler.java:562)
```

**Comment by lalithsuresh** [comment]
@abhizer @mihaibudiu I'm update this milestone to March 29. Let me know if it's appropriate, if not, please close or update the issue as you see fit.

**Comment by abhizer** [comment]
4 of them fail to compile, and one I'm not sure we can support yet (I think it requires support for structs). I will implement the remaining 2 for March 29th release. 

And then I think we can keep this issue open.

**Comment by mihaibudiu** [comment]
the issue was very large to start with.

**Comment by mihaibudiu** [comment]
The cases that crash the compiler should be filed as separate issues, so we can work on them.

**Comment by mihaibudiu** [comment]
For concat I filed https://issues.apache.org/jira/browse/CALCITE-6353 and the fix https://github.com/apache/calcite/pull/3751

**Comment by abhizer** [comment]
`array_insert`, for the following test also fails similar to the above programs. 

```java
    @Test
    public void testArrayInsertFails() {
        this.qs("""
                SELECT array_insert(ARRAY [1, 2, 3], 5, 4);
                 array_insert
                --------------
                 {1, 2, 3, null, 4}
                (1 row)
                """
        );
    }
```

This might also get fixed with: https://github.com/apache/calcite/pull/3751

**Comment by mihaibudiu** [comment]
I will close this issue, even though ARRAY_ZIP is not supported.
It shows up in #1265 anyway.
