### ISSUE TITLE
[SQL] `array_append(null, 1)`: componentType is null for NULL

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1465]
Consider a test as such: 

```java
    public void testArrayAppendNull() {
        this.q("""
                SELECT array_append(null, 1);
                 array_append
                --------------
                 NULL"""
        );
    }
```

We get: 

```
error: This is a bug in the compiler (please report it to the developers): componentType is null for NULL


java.lang.NullPointerException: componentType is null for NULL

	at java.base/java.util.Objects.requireNonNull(Objects.java:360)
	at org.apache.calcite.sql.type.NonNullableAccessors.getComponentTypeOrThrow(NonNullableAccessors.java:52)
	at org.apache.calcite.sql.type.ArrayElementOperandTypeChecker.checkOperandTypes(ArrayElementOperandTypeChecker.java:49)
	at org.apache.calcite.sql.SqlOperator.checkOperandTypes(SqlOperator.java:761)
	at org.apache.calcite.sql.SqlOperator.validateOperands(SqlOperator.java:498)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:347)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:231)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6575)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6562)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:166)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1926)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1911)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:485)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4658)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3840)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:61)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1154)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1125)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:282)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1091)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:797)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:607)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:851)
```

I feel like for null here, it should be turned into `None::<Vec<T>>`.

**Comment by mihaibudiu** [comment]
Filed https://issues.apache.org/jira/browse/CALCITE-6283 for this one

**Comment by abhizer** [comment]
Similar error on: 

```sql
                SELECT ARRAYS_OVERLAP(null, null);
                 arrays_overlap
                ----------------
                 NULL
                (1 row)
```

**Comment by mihaibudiu** [comment]
Filed https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-6348 for OVERLAP

**Comment by mihaibudiu** [comment]
https://github.com/apache/calcite/pull/3746
