### ISSUE TITLE
Kafka test failures setting up the initial connection

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1469]
(Split off from issue #1331.)

CI run 7769573622 failed with:

```
2024-02-03T21:58:07.3625188Z       +test-adapters *failed* | ---- transport::kafka::ft::test::output_test stdout ----
2024-02-03T21:58:07.3627765Z       +test-adapters *failed* | 2024-02-03 21:54:45.951101 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_to
pic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: 
Not leader for partition)
2024-02-03T21:58:07.3631154Z       +test-adapters *failed* | 2024-02-03 21:54:47.051299 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: Meta data fetch error: OperationTimedOut (Local: Timed out)
2024-02-03T21:58:07.3635112Z       +test-adapters *failed* | 2024-02-03 21:54:47.475045 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
2024-02-03T21:58:07.3638487Z       +test-adapters *failed* | 2024-02-03 21:54:47.876955 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: success after 3 tries
2024-02-03T21:58:07.3640721Z       +test-adapters *failed* | 2024-02-03 21:54:47.877581 DEBUG Configured max message size: 999936 ('message.max.bytes=1000000')
2024-02-03T21:58:07.3642804Z       +test-adapters *failed* | thread 'transport::kafka::ft::test::output_test' panicked at crates/adapters/src/transport/kafka/ft/test.rs:577:10:
2024-02-03T21:58:07.3645061Z       +test-adapters *failed* | called `Result::unwrap()` on an `Err` value: Transaction error: Timed out waiting for operation to finish, retry call to resume
2024-02-03T21:58:07.3646293Z 
2024-02-03T21:58:07.3646600Z       +test-adapters *failed* | Caused by:
2024-02-03T21:58:07.3647647Z       +test-adapters *failed* |     Timed out waiting for operation to finish, retry call to resume
2024-02-03T21:58:07.3648985Z       +test-adapters *failed* | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-02-03T21:58:07.3649723Z 
2024-02-03T21:58:07.3649728Z 
2024-02-03T21:58:07.3650022Z       +test-adapters *failed* | failures:
2024-02-03T21:58:07.3650913Z       +test-adapters *failed* |     transport::kafka::ft::test::output_test
```

CI run 7850835766 failed with similar output:

```
2024-02-09T23:52:00.3101814Z       +test-adapters *failed* | ---- transport::kafka::ft::test::output_test stdout ----
2024-02-09T23:52:00.3104551Z       +test-adapters *failed* | 2024-02-09 23:49:56.832331 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
2024-02-09T23:52:00.3107675Z       +test-adapters *failed* | 2024-02-09 23:49:56.934678 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: success after 1 tries
2024-02-09T23:52:00.3109642Z       +test-adapters *failed* | 2024-02-09 23:49:56.935466 DEBUG Configured max message size: 999936 ('message.max.bytes=1000000')
2024-02-09T23:52:00.3111476Z       +test-adapters *failed* | thread 'transport::kafka::ft::test::output_test' panicked at crates/adapters/src/transport/kafka/ft/test.rs:577:10:
2024-02-09T23:52:00.3113760Z       +test-adapters *failed* | called `Result::unwrap()` on an `Err` value: Transaction error: Timed out waiting for operation to finish, retry call to resume
2024-02-09T23:52:00.3115091Z 
2024-02-09T23:52:00.3115451Z       +test-adapters *failed* | Caused by:
2024-02-09T23:52:00.3116628Z       +test-adapters *failed* |     Timed out waiting for operation to finish, retry call to resume
2024-02-09T23:52:00.3118205Z       +test-adapters *failed* | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-02-09T23:52:00.3119078Z 
2024-02-09T23:52:00.3119218Z 
2024-02-09T23:52:00.3119551Z       +test-adapters *failed* | failures:
2024-02-09T23:52:00.3120622Z       +test-adapters *failed* |     transport::kafka::ft::test::output_test
```

CI run 7903635054 also failed with similar output:

```
2024-02-14T15:50:23.6108994Z       +test-adapters *failed* | ---- transport::kafka::ft::test::output_test stdout ----
2024-02-14T15:50:23.6111665Z       +test-adapters *failed* | 2024-02-14 15:48:36.999658 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
2024-02-14T15:50:23.6116065Z       +test-adapters *failed* | 2024-02-14 15:48:37.443050 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
2024-02-14T15:50:23.6119362Z       +test-adapters *failed* | 2024-02-14 15:48:37.644605 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: success after 2 tries
2024-02-14T15:50:23.6121432Z       +test-adapters *failed* | 2024-02-14 15:48:37.645233 DEBUG Configured max message size: 999936 ('message.max.bytes=1000000')
2024-02-14T15:50:23.6123457Z       +test-adapters *failed* | thread 'transport::kafka::ft::test::output_test' panicked at crates/adapters/src/transport/kafka/ft/test.rs:577:10:
2024-02-14T15:50:23.6125827Z       +test-adapters *failed* | called `Result::unwrap()` on an `Err` value: Transaction error: Timed out waiting for operation to finish, retry call to resume
2024-02-14T15:50:23.6126942Z 
2024-02-14T15:50:23.6127242Z       +test-adapters *failed* | Caused by:
2024-02-14T15:50:23.6128211Z       +test-adapters *failed* |     Timed out waiting for operation to finish, retry call to resume
2024-02-14T15:50:23.6129514Z       +test-adapters *failed* | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-02-14T15:50:23.6130230Z 
2024-02-14T15:50:23.6130235Z 
2024-02-14T15:50:23.6130517Z       +test-adapters *failed* | failures:
2024-02-14T15:50:23.6131385Z       +test-adapters *failed* |     transport::kafka::ft::test::output_test
2024-02-14T15:50:23.6132045Z 
2024-02-14T15:50:23.6132820Z       +test-adapters *failed* | test result: FAILED. 91 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 80.58s
```

All of these fail trying to initially set up the connection to Kafka. They have different numbers of retries at the beginning (1, 2, and 3 retries).

**Comment by blp** [comment]
Similar failure [in another CI run](https://github.com/feldera/feldera/actions/runs/8159045410/job/22302935937?pr=1485):

```
      +test-adapters *failed* | ---- transport::kafka::ft::test::output_test stdout ----
      +test-adapters *failed* | 2024-03-05 16:24:15.816675 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
      +test-adapters *failed* | 2024-03-05 16:24:16.180153 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
      +test-adapters *failed* | 2024-03-05 16:24:16.382145 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
      +test-adapters *failed* | 2024-03-05 16:24:16.784273 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: success after 3 tries
      +test-adapters *failed* | 2024-03-05 16:24:16.784729 DEBUG Configured max message size: 999936 ('message.max.bytes=1000000')
      +test-adapters *failed* | thread 'transport::kafka::ft::test::output_test' panicked at crates/adapters/src/transport/kafka/ft/test.rs:577:10:
      +test-adapters *failed* | called `Result::unwrap()` on an `Err` value: Transaction error: Timed out waiting for operation to finish, retry call to resume

      +test-adapters *failed* | Caused by:
      +test-adapters *failed* |     Timed out waiting for operation to finish, retry call to resume
      +test-adapters *failed* | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by blp** [comment]
It's hard to guess the root cause here. The retries suggest that the broker is running slowly. That might mean that extending the timeout would be helpful.

**Comment by blp** [comment]
I merged my PR to increase the initialization timeout. That might actually solve the problem; if not, let's reopen this.

**Comment by blp** [comment]
Similar failure in run 8154490923 (which I believe was prior to the PR to extend the timeout):

```
2024-03-05T10:47:46.3062652Z       +test-adapters *failed* | ---- transport::kafka::ft::test::output_test stdout ----
2024-03-05T10:47:46.3065206Z       +test-adapters *failed* | 2024-03-05 10:46:14.002751 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
2024-03-05T10:47:46.3068986Z       +test-adapters *failed* | 2024-03-05 10:46:14.279702 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: unable to connect to newly created topics, retrying: topic ft_ft_kafka_end_to_end_csv_large_output_topic: Meta data fetch error: NotLeaderForPartition (Broker: Not leader for partition)
2024-03-05T10:47:46.3071817Z       +test-adapters *failed* | 2024-03-05 10:46:14.481951 INFO KafkaResources::create_topics ["ft_ft_kafka_end_to_end_csv_large_output_topic"]: success after 2 tries
2024-03-05T10:47:46.3073569Z       +test-adapters *failed* | 2024-03-05 10:46:14.482785 DEBUG Configured max message size: 999936 ('message.max.bytes=1000000')
2024-03-05T10:47:46.3076050Z       +test-adapters *failed* | thread 'transport::kafka::ft::test::output_test' panicked at crates/adapters/src/transport/kafka/ft/test.rs:577:10:
2024-03-05T10:47:46.3078298Z       +test-adapters *failed* | called `Result::unwrap()` on an `Err` value: Transaction error: Timed out waiting for operation to finish, retry call to resume
2024-03-05T10:47:46.3079431Z 
2024-03-05T10:47:46.3079783Z       +test-adapters *failed* | Caused by:
2024-03-05T10:47:46.3080956Z       +test-adapters *failed* |     Timed out waiting for operation to finish, retry call to resume
2024-03-05T10:47:46.3082508Z       +test-adapters *failed* | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-05T10:47:46.3083508Z 
2024-03-05T10:47:46.3083514Z 
2024-03-05T10:47:46.3083859Z       +test-adapters *failed* | failures:
2024-03-05T10:47:46.3084926Z       +test-adapters *failed* |     transport::kafka::ft::test::output_test
2024-03-05T10:47:46.3085725Z 
2024-03-05T10:47:46.3086501Z       +test-adapters *failed* | test result: FAILED. 94 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 83.21s
```
