### ISSUE TITLE
Kafka test failure for proptest_kafka_input

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1470]
(Split off from issue #1331.)

Run 7936895694 failed with:

```
2024-02-16T22:42:01.6634675Z       +test-adapters | ---- transport::kafka::ft::test::proptest_kafka_input stdout ----
2024-02-16T22:42:01.6639757Z       +test-adapters | 2024-02-16 22:31:16.271133 INFO proptest_kafka_input: Test: Specify invalid Kafka broker address
2024-02-16T22:42:01.6647149Z       +test-adapters | 2024-02-16 22:31:26.273219 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6656435Z       +test-adapters | 2024-02-16 22:31:26.273322 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6666218Z       +test-adapters | 2024-02-16 22:31:26.273350 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2024-02-16T22:42:01.6676707Z       +test-adapters | 2024-02-16 22:31:26.273372 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6686125Z       +test-adapters | 2024-02-16 22:31:26.273394 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6695046Z       +test-adapters | 2024-02-16 22:31:26.273416 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6705059Z       +test-adapters | 2024-02-16 22:31:26.273437 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6713970Z       +test-adapters | 2024-02-16 22:31:26.273459 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6720483Z       +test-adapters | 2024-02-16 22:31:26.273480 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6724558Z       +test-adapters | 2024-02-16 22:31:26.273502 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6730212Z       +test-adapters | 2024-02-16 22:31:26.274085 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic ft_input_test_topic1_input-index: Failed to read metadata for topic ft_input_test_topic1: Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure): BrokerTransportFailure (Local: Broker transport failure)
2024-02-16T22:42:01.6735341Z       +test-adapters | 2024-02-16 22:31:26.274414 INFO proptest_kafka_input: Error: Failed to read index topic ft_input_test_topic1_input-index
2024-02-16T22:42:01.6737877Z       +test-adapters | 2024-02-16 22:31:26.274620 INFO proptest_kafka_input: Test: Specify invalid Kafka topic name
2024-02-16T22:42:01.6742841Z       +test-adapters | 2024-02-16 22:31:26.279005 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic this_topic_does_not_exist_input-index: Error reading metadata for topic this_topic_does_not_exist: Meta data fetch error: UnknownTopicOrPartition (Broker: Unknown topic or partition): UnknownTopicOrPartition (Broker: Unknown topic or partition)
2024-02-16T22:42:01.6747796Z       +test-adapters | 2024-02-16 22:31:26.285867 INFO proptest_kafka_input: Error: Failed to read index topic this_topic_does_not_exist_input-index
2024-02-16T22:42:01.6750232Z       +test-adapters | 2024-02-16 22:31:26.285940 INFO proptest_kafka_input: Building input pipeline
2024-02-16T22:42:01.6752523Z       +test-adapters | 2024-02-16 22:31:26.287833 INFO proptest_kafka_input: Test: Receive from a topic with a single partition
2024-02-16T22:42:01.6754711Z       +test-adapters | 2024-02-16 22:31:26.289655 DEBUG ft_input_test_topic1 has 1 partitions
2024-02-16T22:42:01.6757089Z       +test-adapters | 2024-02-16 22:31:26.290330 INFO Index topic ft_input_test_topic1_input-index does not yet exist, creating with 1 partitions
2024-02-16T22:42:01.6760080Z       +test-adapters | 2024-02-16 22:31:27.554879 DEBUG index topic ft_input_test_topic1_input-index partition 0 has steps 0..0 and watermarks 0..0
2024-02-16T22:42:01.6762411Z       +test-adapters | 2024-02-16 22:31:27.556760 DEBUG ft_input_test_topic2 has 2 partitions
2024-02-16T22:42:01.6765008Z       +test-adapters | 2024-02-16 22:31:27.557057 INFO Index topic ft_input_test_topic2_input-index does not yet exist, creating with 2 partitions
2024-02-16T22:42:01.6770544Z       +test-adapters | 2024-02-16 22:31:28.865620 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic ft_input_test_topic2_input-index: Failed to fetch watermarks for topic ft_input_test_topic2_input-index partition 0: Meta data fetch error: OffsetNotAvailable (Broker: Leader high watermark is not caught up): OffsetNotAvailable (Broker: Leader high watermark is not caught up)
2024-02-16T22:42:01.6775604Z       +test-adapters | thread 'dkw-ft_input_test_topic1' panicked at crates/adapters/src/test/mock_input_consumer.rs:126:13:
2024-02-16T22:42:01.6778145Z       +test-adapters | mock_input_consumer: fatal transport error 'Failed to read index topic ft_input_test_topic2_input-index'
2024-02-16T22:42:01.6780451Z       +test-adapters | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-02-16T22:42:01.6783042Z       +test-adapters | thread 'transport::kafka::ft::test::proptest_kafka_input' panicked at crates/adapters/src/transport/kafka/ft/test.rs:37:40:
2024-02-16T22:42:01.6785264Z       +test-adapters | index out of bounds: the len is 0 but the index is 0
2024-02-16T22:42:01.6787274Z       +test-adapters | 2024-02-16 22:41:26.768414 INFO proptest_kafka_input: Test: Specify invalid Kafka broker address
2024-02-16T22:42:01.6790628Z       +test-adapters | 2024-02-16 22:41:36.771856 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6794831Z       +test-adapters | 2024-02-16 22:41:36.771960 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6799391Z       +test-adapters | 2024-02-16 22:41:36.771984 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2024-02-16T22:42:01.6803972Z       +test-adapters | 2024-02-16 22:41:36.772008 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6808182Z       +test-adapters | 2024-02-16 22:41:36.772029 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6812240Z       +test-adapters | 2024-02-16 22:41:36.772051 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6816443Z       +test-adapters | 2024-02-16 22:41:36.772072 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6819357Z       +test-adapters | 2024-02-16 22:41:36.772093 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6823030Z       +test-adapters | 2024-02-16 22:41:36.772642 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic ft_input_test_topic1_input-index: Failed to read metadata for topic ft_input_test_topic1: Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure): BrokerTransportFailure (Local: Broker transport failure)
2024-02-16T22:42:01.6826165Z       +test-adapters | 2024-02-16 22:41:36.775558 INFO proptest_kafka_input: Error: Failed to read index topic ft_input_test_topic1_input-index
2024-02-16T22:42:01.6827933Z       +test-adapters | 2024-02-16 22:41:36.775636 INFO proptest_kafka_input: Test: Specify invalid Kafka topic name
2024-02-16T22:42:01.6831175Z       +test-adapters | 2024-02-16 22:41:36.782217 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic this_topic_does_not_exist_input-index: Error reading metadata for topic this_topic_does_not_exist: Meta data fetch error: UnknownTopicOrPartition (Broker: Unknown topic or partition): UnknownTopicOrPartition (Broker: Unknown topic or partition)
2024-02-16T22:42:01.6834408Z       +test-adapters | 2024-02-16 22:41:36.788616 INFO proptest_kafka_input: Error: Failed to read index topic this_topic_does_not_exist_input-index
2024-02-16T22:42:01.6835987Z       +test-adapters | 2024-02-16 22:41:36.788679 INFO proptest_kafka_input: Building input pipeline
2024-02-16T22:42:01.6837479Z       +test-adapters | 2024-02-16 22:41:36.792169 INFO proptest_kafka_input: Test: Receive from a topic with a single partition
2024-02-16T22:42:01.6839314Z       +test-adapters | 2024-02-16 22:41:36.794005 DEBUG ft_input_test_topic1 has 1 partitions
2024-02-16T22:42:01.6841008Z       +test-adapters | 2024-02-16 22:41:36.794505 INFO Index topic ft_input_test_topic1_input-index does not yet exist, creating with 1 partitions
2024-02-16T22:42:01.6843073Z       +test-adapters | 2024-02-16 22:41:37.794905 DEBUG index topic ft_input_test_topic1_input-index partition 0 has steps 0..0 and watermarks 0..0
2024-02-16T22:42:01.6844740Z       +test-adapters | 2024-02-16 22:41:37.797456 DEBUG ft_input_test_topic2 has 2 partitions
2024-02-16T22:42:01.6846470Z       +test-adapters | 2024-02-16 22:41:37.798100 INFO Index topic ft_input_test_topic2_input-index does not yet exist, creating with 2 partitions
2024-02-16T22:42:01.6848558Z       +test-adapters | 2024-02-16 22:41:38.798385 DEBUG index topic ft_input_test_topic2_input-index partition 0 has steps 0..0 and watermarks 0..0
2024-02-16T22:42:01.6850772Z       +test-adapters | 2024-02-16 22:41:38.799311 DEBUG index topic ft_input_test_topic2_input-index partition 1 has steps 0..0 and watermarks 0..0
2024-02-16T22:42:01.6852410Z       +test-adapters | 2024-02-16 22:41:38.800512 DEBUG creating Kafka producer for index topics
2024-02-16T22:42:01.6854093Z       +test-adapters | 2024-02-16 22:41:38.832454 INFO proptest_kafka_input: Test: Receive from a topic with multiple partitions
2024-02-16T22:42:01.6855553Z       +test-adapters | 2024-02-16 22:41:39.855524 INFO proptest_kafka_input: Test: pause/resume
2024-02-16T22:42:01.6856836Z       +test-adapters | 2024-02-16 22:41:41.904961 INFO proptest_kafka_input: Test: Disconnect
2024-02-16T22:42:01.6858258Z       +test-adapters | 2024-02-16 22:41:44.295130 INFO proptest_kafka_input: Test: Specify invalid Kafka broker address
2024-02-16T22:42:01.6860530Z       +test-adapters | 2024-02-16 22:41:54.298431 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6863230Z       +test-adapters | 2024-02-16 22:41:54.298537 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6866245Z       +test-adapters | 2024-02-16 22:41:54.298562 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2024-02-16T22:42:01.6869213Z       +test-adapters | 2024-02-16 22:41:54.298596 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6872057Z       +test-adapters | 2024-02-16 22:41:54.298619 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6874811Z       +test-adapters | 2024-02-16 22:41:54.298641 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6877523Z       +test-adapters | 2024-02-16 22:41:54.298670 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6880742Z       +test-adapters | 2024-02-16 22:41:54.298692 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6883659Z       +test-adapters | 2024-02-16 22:41:54.298713 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
2024-02-16T22:42:01.6887714Z       +test-adapters | 2024-02-16 22:41:54.299185 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic ft_input_test_topic1_input-index: Failed to read metadata for topic ft_input_test_topic1: Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure): BrokerTransportFailure (Local: Broker transport failure)
2024-02-16T22:42:01.6891123Z       +test-adapters | 2024-02-16 22:41:54.302827 INFO proptest_kafka_input: Error: Failed to read index topic ft_input_test_topic1_input-index
2024-02-16T22:42:01.6892799Z       +test-adapters | 2024-02-16 22:41:54.302885 INFO proptest_kafka_input: Test: Specify invalid Kafka topic name
2024-02-16T22:42:01.6896064Z       +test-adapters | 2024-02-16 22:41:54.308030 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic this_topic_does_not_exist_input-index: Error reading metadata for topic this_topic_does_not_exist: Meta data fetch error: UnknownTopicOrPartition (Broker: Unknown topic or partition): UnknownTopicOrPartition (Broker: Unknown topic or partition)
2024-02-16T22:42:01.6899465Z       +test-adapters | 2024-02-16 22:41:54.314420 INFO proptest_kafka_input: Error: Failed to read index topic this_topic_does_not_exist_input-index
2024-02-16T22:42:01.6901062Z       +test-adapters | 2024-02-16 22:41:54.314481 INFO proptest_kafka_input: Building input pipeline
2024-02-16T22:42:01.6902585Z       +test-adapters | 2024-02-16 22:41:54.316384 INFO proptest_kafka_input: Test: Receive from a topic with a single partition
2024-02-16T22:42:01.6903994Z       +test-adapters | 2024-02-16 22:41:54.318497 DEBUG ft_input_test_topic1 has 1 partitions
2024-02-16T22:42:01.6905576Z       +test-adapters | 2024-02-16 22:41:54.319159 INFO Index topic ft_input_test_topic1_input-index does not yet exist, creating with 1 partitions
2024-02-16T22:42:01.6907460Z       +test-adapters | 2024-02-16 22:41:55.320377 DEBUG index topic ft_input_test_topic1_input-index partition 0 has steps 0..0 and watermarks 0..0
2024-02-16T22:42:01.6909041Z       +test-adapters | 2024-02-16 22:41:55.323086 DEBUG ft_input_test_topic2 has 2 partitions
2024-02-16T22:42:01.6910596Z       +test-adapters | 2024-02-16 22:41:55.323871 INFO Index topic ft_input_test_topic2_input-index does not yet exist, creating with 2 partitions
2024-02-16T22:42:01.6912449Z       +test-adapters | 2024-02-16 22:41:56.324456 DEBUG index topic ft_input_test_topic2_input-index partition 0 has steps 0..0 and watermarks 0..0
2024-02-16T22:42:01.6914327Z       +test-adapters | 2024-02-16 22:41:56.325241 DEBUG index topic ft_input_test_topic2_input-index partition 1 has steps 0..0 and watermarks 0..0
2024-02-16T22:42:01.6915993Z       +test-adapters | 2024-02-16 22:41:56.326460 DEBUG creating Kafka producer for index topics
2024-02-16T22:42:01.6917463Z       +test-adapters | 2024-02-16 22:41:56.360996 INFO proptest_kafka_input: Test: Receive from a topic with multiple partitions
2024-02-16T22:42:01.6919304Z       +test-adapters | 2024-02-16 22:41:57.365106 INFO proptest_kafka_input: Test: pause/resume
2024-02-16T22:42:01.6920654Z       +test-adapters | 2024-02-16 22:41:59.418462 INFO proptest_kafka_input: Test: Disconnect
2024-02-16T22:42:01.6922377Z       +test-adapters | proptest: Saving this and future failures in /dbsp/crates/adapters/proptest-regressions/transport/kafka/ft/test.txt
2024-02-16T22:42:01.6924558Z       +test-adapters | proptest: If this test was run on a CI system, you may wish to add the following line to your copy of the file. (You may need to create it.)
2024-02-16T22:42:01.6926372Z       +test-adapters | cc 9394e477237187e9d1f1228b221b81d422e0762cb0128724a51752b632ed43dc
2024-02-16T22:42:01.6928159Z       +test-adapters | thread 'transport::kafka::ft::test::proptest_kafka_input' panicked at crates/adapters/src/transport/kafka/ft/test.rs:774:1:
2024-02-16T22:42:01.6929927Z       +test-adapters | Test failed: index out of bounds: the len is 0 but the index is 0.
2024-02-16T22:42:01.6930933Z       +test-adapters | minimal failing input: data = [
2024-02-16T22:42:01.6931630Z       +test-adapters |     [
...thousands of lines of crap...
2024-02-16T22:42:02.6793786Z       +test-adapters |     ],
2024-02-16T22:42:02.6793954Z       +test-adapters | ]
2024-02-16T22:42:02.6794215Z       +test-adapters | 	successes: 0
2024-02-16T22:42:02.6794449Z       +test-adapters | 	local rejects: 0
2024-02-16T22:42:02.6794673Z       +test-adapters | 	global rejects: 0
2024-02-16T22:42:02.6794680Z 
2024-02-16T22:42:02.6794685Z 
2024-02-16T22:42:02.6794690Z 
2024-02-16T22:42:02.6794879Z       +test-adapters | failures:
2024-02-16T22:42:02.6795492Z       +test-adapters |     transport::kafka::ft::test::proptest_kafka_input
2024-02-16T22:42:02.6795508Z 
2024-02-16T22:42:02.6796199Z       +test-adapters | test result: FAILED. 91 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 647.32s
```

**Comment by blp** [comment]
I'm puzzled by this one. This error message is terribly non-specific:

```
2024-02-16T22:42:01.6928159Z       +test-adapters | thread 'transport::kafka::ft::test::proptest_kafka_input' panicked at crates/adapters/src/transport/kafka/ft/test.rs:774:1:
2024-02-16T22:42:01.6929927Z       +test-adapters | Test failed: index out of bounds: the len is 0 but the index is 0.
```

`test.rs:774` as cited by the message is:

```
proptest! {
```

which is no help at all.

**Comment by blp** [comment]
Although I guess that the error must be somewhere in here based on the last log message before failure: 

```
    info!("proptest_kafka_input: Test: Disconnect");
    // Disconnected endpoint should not receive any data.
    endpoint.disconnect();
    sleep(Duration::from_millis(1000));

    producer.send_to_topic(&data, topic1);
    sleep(Duration::from_millis(1000));
    assert_eq!(zset.state().flushed.len(), 0);
```

**Comment by blp** [comment]
I think we can further localize the falure because of the `sleep` calls. The failure occurs less than 1 ms after the `Disconnect` log message:

```
2024-02-16T22:42:01.6920654Z       +test-adapters | 2024-02-16 22:41:59.418462 INFO proptest_kafka_input: Test: Disconnect
2024-02-16T22:42:01.6922377Z       +test-adapters | proptest: Saving this and future failures in /dbsp/crates/adapters/proptest-regressions/transport/kafka/ft/test.txt
```

therefore we must not have reached the first `sleep`, and so the failure must happen in this call:

```
    endpoint.disconnect();
```

**Comment by blp** [comment]
`disconnect` and the code it calls is:

```rust
/// A reader for fault-tolerant Kafka input.
///
/// Code outside this module accesses this as `dyn InputReader`.
struct Reader {
    action: Arc<Mutex<Action>>,
    complete_step: Arc<Mutex<Option<Step>>>,
    unparker: Unparker,
    join_handle: Option<JoinHandle<()>>,
}

impl Reader {
    fn set_action(&self, new_action: Action) {
        let mut action = self.action.lock().unwrap();
        if *action != new_action {
            *action = new_action;
            self.unparker.unpark();
        }
    }
}

impl InputReader for Reader {
// ...
    fn disconnect(&self) {
        self.set_action(Err(ExitRequest));
    }
}
```

and I'm at a loss about how this could yield an "index out of bounds" error.

**Comment by ryzhyk** [comment]
@blp , would it help to enable `RUST_BACKTRACE=1` in CI?

**Comment by blp** [comment]
> @blp , would it help to enable `RUST_BACKTRACE=1` in CI?

Couldn't hurt.

**Comment by blp** [comment]
I merged the PR for better backtraces and I'm going to close it for now, to reopen when we've got another repro.
