### ISSUE TITLE
[SQL] ICE: `array_repeat(123, null)` errors because expressions of different types cannot be added to set: INTEGER NOT NULL ARRAY NOT NULL -> INTEGER NOT NULL ARRAY

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1473]
Consider a test as such: 

```java
    @Test
    public void testArrayRepeat2() {
        this.qs("""
                SELECT array_repeat(123, null);
                 array_repeat
                --------------
                 NULL
                (1 row)
                """
        );
    }

```

It fails to compile with: 

```java
error: This is a bug in the compiler (please report it to the developers): Cannot add expression of different type to set:
set type is RecordType(INTEGER NOT NULL ARRAY NOT NULL EXPR$0) NOT NULL
expression type is RecordType(INTEGER NOT NULL ARRAY EXPR$0) NOT NULL
set is rel#4:LogicalProject.(input=HepRelVertex#3,exprs=[ARRAY_REPEAT(123, null:DECIMAL(38, 10))])
expression is LogicalProject(EXPR$0=[null:INTEGER NOT NULL ARRAY])
  LogicalValues(tuples=[[{ 0 }]])
Type mismatch:
rowtype of original rel: RecordType(INTEGER NOT NULL ARRAY NOT NULL EXPR$0) NOT NULL
rowtype of new rel: RecordType(INTEGER NOT NULL ARRAY EXPR$0) NOT NULL
Difference:
EXPR$0: INTEGER NOT NULL ARRAY NOT NULL -> INTEGER NOT NULL ARRAY



java.lang.AssertionError: Cannot add expression of different type to set:
set type is RecordType(INTEGER NOT NULL ARRAY NOT NULL EXPR$0) NOT NULL
expression type is RecordType(INTEGER NOT NULL ARRAY EXPR$0) NOT NULL
set is rel#4:LogicalProject.(input=HepRelVertex#3,exprs=[ARRAY_REPEAT(123, null:DECIMAL(38, 10))])
expression is LogicalProject(EXPR$0=[null:INTEGER NOT NULL ARRAY])
  LogicalValues(tuples=[[{ 0 }]])
Type mismatch:
rowtype of original rel: RecordType(INTEGER NOT NULL ARRAY NOT NULL EXPR$0) NOT NULL
rowtype of new rel: RecordType(INTEGER NOT NULL ARRAY EXPR$0) NOT NULL
Difference:
EXPR$0: INTEGER NOT NULL ARRAY NOT NULL -> INTEGER NOT NULL ARRAY


	at org.apache.calcite.plan.RelOptUtil.verifyTypeEquivalence(RelOptUtil.java:401)
	at org.apache.calcite.plan.hep.HepRuleCall.transformTo(HepRuleCall.java:60)
	at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:273)
	at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:288)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:317)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337)
	at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556)
	at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:420)
	at org.apache.calcite.plan.hep.HepPlanner.executeRuleInstance(HepPlanner.java:243)
	at org.apache.calcite.plan.hep.HepInstruction$RuleInstance$State.execute(HepInstruction.java:178)
	at org.apache.calcite.plan.hep.HepPlanner.lambda$executeProgram$0(HepPlanner.java:211)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:210)
	at org.apache.calcite.plan.hep.HepProgram$State.execute(HepProgram.java:118)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:205)
	at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:191)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.optimize(CalciteCompiler.java:561)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:854)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:254)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:310)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:330)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.compare(SqlIoTest.java:145)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.q(SqlIoTest.java:172)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:239)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:247)
	at org.dbsp.sqlCompiler.compiler.sql.simple.ArrayFunctionTests.testArrayRepeat2(ArrayFunctionTests.java:514)

```

**Comment by mihaibudiu** [comment]
I have filed https://issues.apache.org/jira/browse/CALCITE-6286

**Comment by mihaibudiu** [comment]
Turns out that the function definition was changed between Spark 3.4.0 and 3.4.2.
https://spark.apache.org/docs/3.4.0/api/sql/index.html#array_insert
https://spark.apache.org/docs/3.4.2/api/sql/index.html#array_insert
This is just bad software engineering.
So we can probably close this issue and use the spec from the existing function.

**Comment by mihaibudiu** [comment]
I am commenting on the wrong issue

**Comment by mihaibudiu** [comment]
https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-6349
https://github.com/apache/calcite/pull/3747
