### ISSUE TITLE
[SQL] ICE while compiling: `ARRAY_REPEAT('a', 6)` RuntimeException can't cast java.lang.String to java.util.List

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1474]
Consider a function as such: 

```java
    @Test
    public void testArrayRepeat3() {
        this.qs("""
                SELECT array_repeat( 'a', 6);
                 array_repeat
                --------------
                 { a, a, a, a, a, a}
                (1 row)
                """
        );
    }
```

Fails with: 
```java
error: This is a bug in the compiler (please report it to the developers): While compiling [ARRAY_REPEAT('a', 6)]


java.lang.RuntimeException: While compiling [ARRAY_REPEAT('a', 6)]

	at org.apache.calcite.rex.RexExecutable.compile(RexExecutable.java:73)
	at org.apache.calcite.rex.RexExecutable.<init>(RexExecutable.java:53)
	at org.apache.calcite.rex.RexExecutorImpl.reduce(RexExecutorImpl.java:137)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressionsInternal(ReduceExpressionsRule.java:774)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressions(ReduceExpressionsRule.java:714)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:313)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337)
	at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556)
	at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:420)
	at org.apache.calcite.plan.hep.HepPlanner.executeRuleInstance(HepPlanner.java:243)
	at org.apache.calcite.plan.hep.HepInstruction$RuleInstance$State.execute(HepInstruction.java:178)
	at org.apache.calcite.plan.hep.HepPlanner.lambda$executeProgram$0(HepPlanner.java:211)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:210)
	at org.apache.calcite.plan.hep.HepProgram$State.execute(HepProgram.java:118)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:205)
	at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:191)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.optimize(CalciteCompiler.java:561)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:854)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:254)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:310)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:330)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.compare(SqlIoTest.java:145)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.q(SqlIoTest.java:172)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:239)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:247)
	at org.dbsp.sqlCompiler.compiler.sql.simple.ArrayFunctionTests.testArrayRepeat3(ArrayFunctionTests.java:526)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.codehaus.commons.compiler.CompileException: Line 3, Column 22: Cannot cast "java.lang.String" to "java.util.List"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:13014)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5221)
	at org.codehaus.janino.UnitCompiler.access$8800(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$16.visitCast(UnitCompiler.java:4730)
	at org.codehaus.janino.UnitCompiler$16.visitCast(UnitCompiler.java:4711)
	at org.codehaus.janino.Java$Cast.accept(Java.java:5283)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4711)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5854)
	at org.codehaus.janino.UnitCompiler.access$3800(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$7.visitRvalue(UnitCompiler.java:2766)
	at org.codehaus.janino.UnitCompiler$7.visitRvalue(UnitCompiler.java:2754)
	at org.codehaus.janino.Java$Rvalue.accept(Java.java:4498)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:2754)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5824)
	at org.codehaus.janino.UnitCompiler.compileGet2(UnitCompiler.java:5797)
	at org.codehaus.janino.UnitCompiler.access$9900(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$16.visitNewInitializedArray(UnitCompiler.java:4746)
	at org.codehaus.janino.UnitCompiler$16.visitNewInitializedArray(UnitCompiler.java:4711)
	at org.codehaus.janino.Java$NewInitializedArray.accept(Java.java:5770)
	at org.codehaus.janino.UnitCompiler.compileGet(UnitCompiler.java:4711)
	at org.codehaus.janino.UnitCompiler.compileGetValue(UnitCompiler.java:5854)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2848)
	at org.codehaus.janino.UnitCompiler.access$2800(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1590)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1575)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3888)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1575)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1661)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3658)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3329)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1447)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1420)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:829)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:442)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:422)
	at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:418)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1688)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:418)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:392)
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:236)
	at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:363)
	at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:361)
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:371)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:361)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:264)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:294)
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:288)
	at org.apache.calcite.rex.RexExecutable.compile(RexExecutable.java:64)
	... 55 more
```

**Comment by mihaibudiu** [comment]
I also submitted a fix: https://github.com/apache/calcite/pull/3745
