### ISSUE TITLE
FP test failures on ARM

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1519]
here is my run of `mvn package` when running on Apple M2 Max:

(here is maybe some helpful info on what's causing it: https://stackoverflow.com/questions/64036879/differing-floating-point-calculation-results-between-x86-64-and-armv8-2-a)

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] dbsp-compiler                                                      [pom]
[INFO] SQL-compiler                                                       [jar]
[INFO] slt                                                                [jar]
[INFO]
[INFO] ---------------------< com.feldera:dbsp-compiler >----------------------
[INFO] Building dbsp-compiler 1.0-SNAPSHOT                                [1/3]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] ----------------------< com.feldera:SQL-compiler >----------------------
[INFO] Building SQL-compiler 1.0-SNAPSHOT                                 [2/3]
[INFO]   from SQL-compiler/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- dependency:3.6.0:unpack (unpack-parser-template) @ SQL-compiler ---
[INFO] Configured Artifact: org.apache.calcite:calcite-core:?:jar
[INFO]
[INFO] --- resources:3.3.1:copy-resources (copy-fmpp-resources) @ SQL-compiler ---
[INFO] Copying 3 resources from src/main/codegen to target/codegen
[INFO]
[INFO] --- fmpp:1.0:generate (generate-fmpp-sources) @ SQL-compiler ---
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/freemarker/freemarker/maven-metadata.xml
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/oro/oro/maven-metadata.xml
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/beanshell/bsh/maven-metadata.xml
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/beanshell/bsh/maven-metadata.xml (276 B at 859 B/s)
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/xml-resolver/xml-resolver/maven-metadata.xml
- Executing: Parser.jj
log4j:WARN No appenders could be found for logger (freemarker.cache).
log4j:WARN Please initialize the log4j system properly.
[INFO] Done
[INFO]
[INFO] --- javacc:2.4:javacc (javacc) @ SQL-compiler ---
Java Compiler Compiler Version 4.0 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/javacc/Parser.jj . . .
Note: UNICODE_INPUT option is specified. Please make sure you create the parser/lexer using a Reader with the correct character encoding.
Warning: Lookahead adequacy checking not being performed since option LOOKAHEAD is more than 1.  Set option FORCE_LA_CHECK to true to force checking.
Parser generated with 0 errors and 1 warnings.
[INFO] Processed 1 grammar
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ SQL-compiler ---
[INFO] skip non existing resourceDirectory /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/src/main/resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ SQL-compiler ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 380 source files with javac [debug target 19] to target/classes
[WARNING] system modules path not set in conjunction with -source 19
[WARNING] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/org/dbsp/generated/parser/SimpleCharStream.java:[206,14] deprecated item is not annotated with @Deprecated
[WARNING] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/org/dbsp/generated/parser/SimpleCharStream.java:[215,14] deprecated item is not annotated with @Deprecated
[INFO] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/IndexOperator.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/simulator/operators/IndexOperator.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ SQL-compiler ---
[INFO] Copying 3 resources from src/test/resources to target/test-classes
[INFO]
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ SQL-compiler ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 82 source files with javac [debug target 19] to target/test-classes
[WARNING] system modules path not set in conjunction with -source 19
[WARNING] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/org/dbsp/generated/parser/SimpleCharStream.java:[206,14] deprecated item is not annotated with @Deprecated
[WARNING] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/org/dbsp/generated/parser/SimpleCharStream.java:[215,14] deprecated item is not annotated with @Deprecated
[INFO] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/org/dbsp/generated/parser/DbspParserImpl.java: /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/org/dbsp/generated/parser/DbspParserImpl.java uses unchecked or unsafe operations.
[INFO] /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/generated-sources/org/dbsp/generated/parser/DbspParserImpl.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- surefire:3.0.0-M7:test (default-test) @ SQL-compiler ---
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.OtherTests



[WARNING] Tests run: 29, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 159.746 s - in org.dbsp.sqlCompiler.compiler.sql.OtherTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.DBSPCompilerTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.dbsp.sqlCompiler.compiler.sql.DBSPCompilerTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.suites.TpcDsTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.dbsp.sqlCompiler.compiler.sql.suites.TpcDsTest
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.suites.TpchTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.317 s - in org.dbsp.sqlCompiler.compiler.sql.suites.TpchTest
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.suites.nexmark.NexmarkTest
[WARNING] Tests run: 14, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 13.656 s - in org.dbsp.sqlCompiler.compiler.sql.suites.nexmark.NexmarkTest
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.MultiViewTests
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.765 s - in org.dbsp.sqlCompiler.compiler.sql.simple.MultiViewTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.OptimizedIncrementalTests
[WARNING] Tests run: 95, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 25.536 s - in org.dbsp.sqlCompiler.compiler.sql.simple.OptimizedIncrementalTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.TopKTests
[WARNING] Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 4.91 s - in org.dbsp.sqlCompiler.compiler.sql.simple.TopKTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.NaiveIncrementalTests
[WARNING] Tests run: 95, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 21.416 s - in org.dbsp.sqlCompiler.compiler.sql.simple.NaiveIncrementalTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.ArrayTests
[WARNING] Tests run: 21, Failures: 0, Errors: 0, Skipped: 6, Time elapsed: 5.05 s - in org.dbsp.sqlCompiler.compiler.sql.simple.ArrayTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.TimeTests
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.707 s - in org.dbsp.sqlCompiler.compiler.sql.simple.TimeTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.PivotTests
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.303 s - in org.dbsp.sqlCompiler.compiler.sql.simple.PivotTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.ArrayFunctionsTests
[WARNING] Tests run: 17, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 8.203 s - in org.dbsp.sqlCompiler.compiler.sql.simple.ArrayFunctionsTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.EndToEndTests
[WARNING] Tests run: 95, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 19.571 s - in org.dbsp.sqlCompiler.compiler.sql.simple.EndToEndTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.CastTests
[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 2.13 s - in org.dbsp.sqlCompiler.compiler.sql.simple.CastTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.simple.TrigonometryTests
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.486 s - in org.dbsp.sqlCompiler.compiler.sql.simple.TrigonometryTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.ComplexQueriesTest
[WARNING] Tests run: 8, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 10.646 s - in org.dbsp.sqlCompiler.compiler.sql.ComplexQueriesTest
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.TinyintTests
[WARNING] Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 5.182 s - in org.dbsp.sqlCompiler.compiler.sql.TinyintTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.streaming.StreamingTests

[WARNING] Tests run: 8, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 137.256 s - in org.dbsp.sqlCompiler.compiler.sql.streaming.StreamingTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.adapters.AvroSchemaTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s - in org.dbsp.sqlCompiler.compiler.sql.adapters.AvroSchemaTest
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresBoolTests
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.664 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresBoolTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresTimestampTests
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.244 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresTimestampTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresFloat8Part2Tests
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.303 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresFloat8Part2Tests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresInt2Tests
[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 4.576 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresInt2Tests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresAggregatesTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.644 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresAggregatesTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresTimeTests
[WARNING] Tests run: 8, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 2.742 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresTimeTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresNumericTests
Preserved runtime storage at.............................................
failures:

---- test13 stdout ----
R: ("2.718281828459045",)x1
L: ("2.718281828459046",)x1
thread 'test13' panicked at src/lib.rs:12035:5:

    mvn test -Dtest=PostgresNumericTests#testExp
    select exp(1.0)
Preserved runtime storage at: "/var/folders/jn/j2db_rfj7p9b_fh7z7c4gkl80000gn/T/.tmp6RxNZi" due to panic

---- test15 stdout ----
R: ("2.718281828459045",)x1
L: ("2.718281828459046",)x1
thread 'test15' panicked at src/lib.rs:13725:5:

    mvn test -Dtest=PostgresNumericTests#testExp
    select exp(1.0::numeric(25, 10))
Preserved runtime storage at: "/var/folders/jn/j2db_rfj7p9b_fh7z7c4gkl80000gn/T/.tmpCncUjk" due to panic


failures:
    test13
    test15

test result: FAILED. 53 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.12s

erved runtime storage at: "/var/folders/jn/j2db_rfj7p9b_fh7z7c4gkl80000gn/T/.tmpyiDHsU" due to panic
Preserved runtime storage at: "/var/folders/jn/j2db_rfj7p9b_fh7z7c4gkl80000gn/T/.tmpX8Se0w" due to panic
error: test failed, to rerun pass `--lib`
[ERROR] Tests run: 26, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 23.997 s <<< FAILURE! - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresNumericTests
[ERROR] org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresNumericTests  Time elapsed: 22.109 s  <<< ERROR!
java.lang.RuntimeException: Process failed with exit code 101
	at org.dbsp.util.Utilities.runProcess(Utilities.java:255)
	at org.dbsp.util.Utilities.runProcess(Utilities.java:260)
	at org.dbsp.util.Utilities.compile(Utilities.java:274)
	at org.dbsp.util.Utilities.compileAndTestRust(Utilities.java:281)
	at org.dbsp.sqlCompiler.compiler.sql.BaseSQLTests.runAllTests(BaseSQLTests.java:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresGroupingSetsTests
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresGroupingSetsTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresInt8Tests
[WARNING] Tests run: 6, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 9.84 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresInt8Tests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresArrayTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.914 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresArrayTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresIntervalTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.903 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresIntervalTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresDateTests
[INFO] Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.115 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresDateTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresFloat8Tests
Preserved runtime storage at:.............................................................................. 88/238
..F..F.................................................................................. 176/238
..............................................................
failures:

---- test181 stdout ----
R: (Some("1004.3"), Some("10.014312837827033"))x1
L: (Some("1004.3"), Some("10.014312837827035"))x1
L: (Some("123456789012340000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), Some("4979338592347646000000000000000000000000000000000000000000000000000"))x1
R: (Some("123456789012340000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), Some("4979338592347648000000000000000000000000000000000000000000000000000"))x1
thread 'test181' panicked at src/lib.rs:19981:5:

    mvn test -Dtest=PostgresFloat8Tests#testSelect
    SELECT f.f1, cbrt(f.f1) AS cbrt_f1 FROM FLOAT8_TBL f
Preserved runtime storage at: "/var/folders/jn/j2db_rfj7p9b_fh7z7c4gkl80000gn/T/.tmpBu10AH" due to panierror: test failed, to rerun pass `--lib`
.3"), Some("10.014312837827033"))x1
L: (Some("1004.3"), Some("10.014312837827035"))x1
L: (Some("123456789012340000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), Some("4979338592347646000000000000000000000000000000000000000000000000000"))x1
R: (Some("123456789012340000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), Some("4979338592347648000000000000000000000000000000000000000000000000000"))x1
thread 'test180' panicked at src/lib.rs:19870:5:

    mvn test -Dtest=PostgresFloat8Tests#testSelect
    SELECT f.f1, cbrt(f.f1) AS cbrt_f1 FROM FLOAT8_TBL f
Preserved runtime storage at: "/var/folders/jn/j2db_rfj7p9b_fh7z7c4gkl80000gn/T/.tmp2ztPuP" due to panic


failures:
    test180
    test181

test result: FAILED. 236 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s

[ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 12.262 s <<< FAILURE! - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresFloat8Tests
[ERROR] org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresFloat8Tests  Time elapsed: 12.173 s  <<< ERROR!
java.lang.RuntimeException: Process failed with exit code 101
	at org.dbsp.util.Utilities.runProcess(Utilities.java:255)
	at org.dbsp.util.Utilities.runProcess(Utilities.java:260)
	at org.dbsp.util.Utilities.compile(Utilities.java:274)
	at org.dbsp.util.Utilities.compileAndTestRust(Utilities.java:281)
	at org.dbsp.sqlCompiler.compiler.sql.BaseSQLTests.runAllTests(BaseSQLTests.java:197)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresStringTests
[WARNING] Tests run: 42, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 18.518 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresStringTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresCaseTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.942 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresCaseTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresFloat4Tests
[WARNING] Tests run: 10, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 4.125 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresFloat4Tests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresCollateTests
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.781 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresCollateTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresInt4Tests
[WARNING] Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 5.396 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresInt4Tests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresLimitTests
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 4.809 s - in org.dbsp.sqlCompiler.compiler.sql.postgres.PostgresLimitTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.ParserTests
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in org.dbsp.sqlCompiler.compiler.sql.ParserTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.mysql.DateFormatsTests
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 2.025 s - in org.dbsp.sqlCompiler.compiler.sql.mysql.DateFormatsTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.mysql.VarbinaryTests
[WARNING] Tests run: 10, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 4.5 s - in org.dbsp.sqlCompiler.compiler.sql.mysql.VarbinaryTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.mysql.TimestampdiffTests
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.116 s - in org.dbsp.sqlCompiler.compiler.sql.mysql.TimestampdiffTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.CatalogTests
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.349 s - in org.dbsp.sqlCompiler.compiler.sql.CatalogTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.functions.FunctionsTest
[WARNING] Tests run: 31, Failures: 0, Errors: 0, Skipped: 5, Time elapsed: 22.778 s - in org.dbsp.sqlCompiler.compiler.sql.functions.FunctionsTest
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.quidem.FoodmartPivotTests
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 15.935 s - in org.dbsp.sqlCompiler.compiler.sql.quidem.FoodmartPivotTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.quidem.AggTests
[WARNING] Tests run: 9, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 13.883 s - in org.dbsp.sqlCompiler.compiler.sql.quidem.AggTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.quidem.AggScottTests
[WARNING] Tests run: 14, Failures: 0, Errors: 0, Skipped: 7, Time elapsed: 23.922 s - in org.dbsp.sqlCompiler.compiler.sql.quidem.AggScottTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.quidem.FoodmartBaseTests
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 7.923 s - in org.dbsp.sqlCompiler.compiler.sql.quidem.FoodmartBaseTests
[INFO] Running org.dbsp.sqlCompiler.compiler.sql.NegativeParserTests
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 s - in org.dbsp.sqlCompiler.compiler.sql.NegativeParserTests
[INFO] Running org.dbsp.simulator.SimulatorTests
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.043 s - in org.dbsp.simulator.SimulatorTests
Executed 3024 Rust tests
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   PostgresFloat8Tests>BaseSQLTests.runAllTests:197 » Runtime Process failed with exit code 101
[ERROR]   PostgresNumericTests>BaseSQLTests.runAllTests:197 » Runtime Process failed with exit code 101
[INFO]
[ERROR] Tests run: 782, Failures: 0, Errors: 2, Skipped: 63
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dbsp-compiler 1.0-SNAPSHOT:
[INFO]
[INFO] dbsp-compiler ...................................... SUCCESS [  0.001 s]
[INFO] SQL-compiler ....................................... FAILURE [12:00 min]
[INFO] slt ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:00 min
[INFO] Finished at: 2024-03-11T10:33:36-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project SQL-compiler:
[ERROR]
[ERROR] Please refer to /Users/gerdzellweger/workspace/feldera/sql-to-dbsp-compiler/SQL-compiler/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :SQL-compiler
```

**Comment by gz** [comment]
I think this is fixed
