### ISSUE TITLE
[SQL] ICE: TIME + INTERVAL '25' DAYS results in ArithmeticException value out of range

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1658]
While implementing arithmetic operations for TIME and INTERVAL types, the following test results in an `ArithmeticException: Value 2160000000 out of range` during Calcite optimization. 

```java
    @Test
    public void testTimeAddInterval() {
        this.qs("""
                SELECT '12:34:56'::time + INTERVAL '25' DAYS;
                   time
                ---------
                 12:34:56
                (1 row)
                """
        );
    }
```

24 days is still within the range, breaks at 25. 

Stack trace: 

```java
error: This is a bug in the compiler (please report it to the developers): Value 2160000000 out of range


java.lang.ArithmeticException: Value 2160000000 out of range

	at org.apache.calcite.linq4j.tree.Primitive.checkRoundedRange(Primitive.java:383)
	at org.apache.calcite.linq4j.tree.Primitive.numberValue(Primitive.java:408)
	at org.apache.calcite.linq4j.tree.Expressions.constant(Expressions.java:575)
	at org.apache.calcite.linq4j.tree.OptimizeShuttle.visit(OptimizeShuttle.java:301)
	at org.apache.calcite.linq4j.tree.UnaryExpression.accept(UnaryExpression.java:39)
	at org.apache.calcite.linq4j.tree.BinaryExpression.accept(BinaryExpression.java:47)
	at org.apache.calcite.linq4j.tree.Expressions.acceptExpressions(Expressions.java:3214)
	at org.apache.calcite.linq4j.tree.MethodCallExpression.accept(MethodCallExpression.java:63)
	at org.apache.calcite.linq4j.tree.UnaryExpression.accept(UnaryExpression.java:38)
	at org.apache.calcite.linq4j.tree.TernaryExpression.accept(TernaryExpression.java:47)
	at org.apache.calcite.linq4j.tree.Expressions.acceptExpressions(Expressions.java:3214)
	at org.apache.calcite.linq4j.tree.NewArrayExpression.accept(NewArrayExpression.java:49)
	at org.apache.calcite.linq4j.tree.GotoStatement.accept(GotoStatement.java:64)
	at org.apache.calcite.linq4j.tree.BlockBuilder.optimize(BlockBuilder.java:455)
	at org.apache.calcite.linq4j.tree.BlockBuilder.toBlock(BlockBuilder.java:340)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:102)
	at org.apache.calcite.rex.RexExecutorImpl.compile(RexExecutorImpl.java:68)
	at org.apache.calcite.rex.RexExecutorImpl.reduce(RexExecutorImpl.java:133)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressionsInternal(ReduceExpressionsRule.java:774)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule.reduceExpressions(ReduceExpressionsRule.java:714)
	at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:313)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337)
	at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556)
	at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:420)
	at org.apache.calcite.plan.hep.HepPlanner.executeRuleInstance(HepPlanner.java:243)
	at org.apache.calcite.plan.hep.HepInstruction$RuleInstance$State.execute(HepInstruction.java:178)
	at org.apache.calcite.plan.hep.HepPlanner.lambda$executeProgram$0(HepPlanner.java:211)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:210)
	at org.apache.calcite.plan.hep.HepProgram$State.execute(HepProgram.java:118)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:205)
	at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:191)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteOptimizer$CalciteOptimizerStep.optimize(CalciteOptimizer.java:32)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteOptimizer.apply(CalciteOptimizer.java:93)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.optimize(CalciteCompiler.java:425)
	at org.dbsp.sqlCompiler.compiler.frontend.calciteCompiler.CalciteCompiler.compile(CalciteCompiler.java:729)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileInternal(DBSPCompiler.java:275)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:331)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.compileStatement(DBSPCompiler.java:351)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.compare(SqlIoTest.java:145)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.q(SqlIoTest.java:190)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:277)
	at org.dbsp.sqlCompiler.compiler.sql.SqlIoTest.qs(SqlIoTest.java:286)
	at org.dbsp.sqlCompiler.compiler.sql.functions.FunctionsTest.testTimeAddInterval(FunctionsTest.java:2213)
```

**Comment by abhizer** [comment]
Here, `INTERVAL '25' DAYS` is a `ShortInterval` while I think it should be a `LongInterval`.

**Comment by mihaibudiu** [comment]
In Calcite it is a long interval. They should simplify `time + longinterval` to ``time`, but they don't. They overflow during the computation.

**Comment by mihaibudiu** [comment]
Filed a fix with Calcite: https://github.com/apache/calcite/pull/3765
