### ISSUE TITLE
Kafka test failure for ` mock_input_consumer: non-fatal transport error '0.0.0.0:9092/0: 2 request(s) timed out: disconnect (after 1001ms in state APIVERSION_QUERY)'`

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1830]
This occurred for a CI run with logs at https://github.com/feldera/feldera/actions/runs/9353411601/job/25743842583. The important output is:

```
      +test-adapters | 2024-06-03 16:01:25.904183 INFO proptest_kafka_input: Test: Specify invalid Kafka broker address
      +test-adapters | 2024-06-03 16:01:35.907532 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907662 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907696 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907728 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907756 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
      +test-adapters | 2024-06-03 16:01:35.907784 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907822 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907852 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907880 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.907908 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:01:35.908383 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic ft_input_test_topic1_input-index: Failed to read metadata for topic ft_input_test_topic1: Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure): BrokerTransportFailure (Local: Broker transport failure)
      +test-adapters | 2024-06-03 16:01:35.916265 INFO proptest_kafka_input: Error: Failed to read index topic ft_input_test_topic1_input-index
      +test-adapters | 2024-06-03 16:01:35.916367 INFO proptest_kafka_input: Test: Specify invalid Kafka topic name
      +test-adapters | 2024-06-03 16:01:35.921750 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic this_topic_does_not_exist_input-index: Error reading metadata for topic this_topic_does_not_exist: Meta data fetch error: UnknownTopicOrPartition (Broker: Unknown topic or partition): UnknownTopicOrPartition (Broker: Unknown topic or partition)
      +test-adapters | 2024-06-03 16:01:35.928043 INFO proptest_kafka_input: Error: Failed to read index topic this_topic_does_not_exist_input-index
      +test-adapters | 2024-06-03 16:01:35.928131 INFO proptest_kafka_input: Building input pipeline
      +test-adapters | 2024-06-03 16:01:35.930326 INFO proptest_kafka_input: Test: Receive from a topic with a single partition
      +test-adapters | 2024-06-03 16:01:35.932443 DEBUG ft_input_test_topic1 has 1 partitions
      +test-adapters | 2024-06-03 16:01:35.933071 INFO Index topic ft_input_test_topic1_input-index does not yet exist, creating with 1 partitions
      +test-adapters | 2024-06-03 16:01:36.932969 DEBUG index topic ft_input_test_topic1_input-index partition 0 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:01:36.936240 DEBUG ft_input_test_topic2 has 2 partitions
      +test-adapters | 2024-06-03 16:01:36.936848 INFO Index topic ft_input_test_topic2_input-index does not yet exist, creating with 2 partitions
      +test-adapters | 2024-06-03 16:01:37.936742 DEBUG index topic ft_input_test_topic2_input-index partition 0 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:01:37.937174 DEBUG index topic ft_input_test_topic2_input-index partition 1 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:01:37.938575 DEBUG creating Kafka producer for index topics
      +test-adapters | 2024-06-03 16:01:38.942218 INFO Kafka non-fatal error: Meta data fetch error: TimedOutQueue (Local: Timed out in queue)
      +test-adapters | thread 'producer polling thread' panicked at crates/adapters/src/test/mock_input_consumer.rs:126:13:
      +test-adapters | mock_input_consumer: non-fatal transport error '0.0.0.0:9092/0: 2 request(s) timed out: disconnect (after 1001ms in state APIVERSION_QUERY)'
      +test-adapters | stack backtrace:
      +test-adapters |    0: rust_begin_unwind
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
      +test-adapters |    1: core::panicking::panic_fmt
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
      +test-adapters |    2: <dbsp_adapters::test::mock_input_consumer::MockInputConsumer as dbsp_adapters::transport::InputConsumer>::error
      +test-adapters |              at ./src/test/mock_input_consumer.rs:126:13
      +test-adapters |    3: <dbsp_adapters::transport::kafka::ft::input::IndexProducerContext as rdkafka::client::ClientContext>::error
      +test-adapters |              at ./src/transport/kafka/ft/input.rs:719:13
      +test-adapters |    4: rdkafka::client::native_error_cb
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rdkafka-0.34.0/src/client.rs:513:5
      +test-adapters |    5: rd_kafka_poll_cb
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rdkafka-sys-4.7.0+2.3.0/librdkafka/src/rdkafka.c:3863:25
      +test-adapters |    6: rd_kafka_op_handle
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rdkafka-sys-4.7.0+2.3.0/librdkafka/src/rdkafka_op.c:925:23
      +test-adapters |    7: rd_kafka_q_serve
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rdkafka-sys-4.7.0+2.3.0/librdkafka/src/rdkafka_queue.c:578:23
      +test-adapters |    8: rd_kafka_poll
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rdkafka-sys-4.7.0+2.3.0/librdkafka/src/rdkafka.c:4022:13
      +test-adapters |    9: rdkafka::producer::base_producer::BaseProducer<C,Part>::poll
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rdkafka-0.34.0/src/producer/base_producer.rs:375:18
      +test-adapters |   10: <rdkafka::producer::base_producer::ThreadedProducer<C,Part> as rdkafka::config::FromClientConfigAndContext<C>>::from_config_and_context::{{closure}}
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rdkafka-0.34.0/src/producer/base_producer.rs:621:33
      +test-adapters | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
      +test-adapters | thread 'dkw-ft_input_test_topic1' panicked at crates/adapters/src/transport/kafka/ft/input.rs:456:34:
      +test-adapters | called `Result::unwrap()` on an `Err` value: PoisonError { .. }
      +test-adapters | stack backtrace:
      +test-adapters |    0: rust_begin_unwind
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
      +test-adapters |    1: core::panicking::panic_fmt
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
      +test-adapters |    2: core::result::unwrap_failed
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
      +test-adapters |    3: core::result::Result<T,E>::unwrap
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
      +test-adapters |    4: dbsp_adapters::transport::kafka::ft::input::WorkerThread::run
      +test-adapters |              at ./src/transport/kafka/ft/input.rs:456:13
      +test-adapters |    5: dbsp_adapters::transport::kafka::ft::input::WorkerThread::spawn::{{closure}}
      +test-adapters |              at ./src/transport/kafka/ft/input.rs:311:37
      +test-adapters | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
      +test-adapters | 2024-06-03 16:01:39.824001 WARN Failure while terminating thread: Any { .. }
      +test-adapters | thread 'transport::kafka::ft::test::proptest_kafka_input' panicked at crates/adapters/src/transport/kafka/ft/test.rs:36:6:
      +test-adapters | called `Result::unwrap()` on an `Err` value: ()
      +test-adapters | stack backtrace:
      +test-adapters |    0: rust_begin_unwind
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
      +test-adapters |    1: core::panicking::panic_fmt
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
      +test-adapters |    2: core::result::unwrap_failed
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
      +test-adapters |    3: core::result::Result<T,E>::unwrap
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
      +test-adapters |    4: dbsp_adapters::transport::kafka::ft::test::wait_for_output_ordered
      +test-adapters |              at ./src/transport/kafka/ft/test.rs:32:5
      +test-adapters |    5: dbsp_adapters::transport::kafka::ft::test::test_ft_kafka_input
      +test-adapters |              at ./src/transport/kafka/ft/test.rs:719:5
      +test-adapters |    6: dbsp_adapters::transport::kafka::ft::test::proptest_kafka_input::{{closure}}
      +test-adapters |              at ./src/transport/kafka/ft/test.rs:772:9
      +test-adapters |    7: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:262:13
      +test-adapters |    8: proptest::test_runner::runner::call_test::{{closure}}
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/test_runner/runner.rs:256:49
      +test-adapters |    9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
      +test-adapters |   10: std::panicking::try::do_call
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      +test-adapters |   11: __rust_try
      +test-adapters |   12: std::panicking::try
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      +test-adapters |   13: std::panic::catch_unwind
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      +test-adapters |   14: proptest::test_runner::runner::call_test
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/test_runner/runner.rs:256:9
      +test-adapters |   15: proptest::test_runner::runner::TestRunner::run_one_with_replay
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/test_runner/runner.rs:722:22
      +test-adapters |   16: proptest::test_runner::runner::TestRunner::gen_and_run_case
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/test_runner/runner.rs:664:23
      +test-adapters |   17: proptest::test_runner::runner::TestRunner::run_in_process_with_replay
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/test_runner/runner.rs:613:26
      +test-adapters |   18: proptest::test_runner::runner::TestRunner::run_in_process
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/test_runner/runner.rs:570:9
      +test-adapters |   19: proptest::test_runner::runner::TestRunner::run
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/test_runner/runner.rs:413:13
      +test-adapters |   20: dbsp_adapters::transport::kafka::ft::test::proptest_kafka_input
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/sugar.rs:163:17
      +test-adapters |   21: dbsp_adapters::transport::kafka::ft::test::proptest_kafka_input::{{closure}}
      +test-adapters |              at /tmp/earthly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proptest-1.4.0/src/sugar.rs:159:28
      +test-adapters |   22: core::ops::function::FnOnce::call_once
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
      +test-adapters |   23: core::ops::function::FnOnce::call_once
      +test-adapters |              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
      +test-adapters | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
      +test-adapters | 2024-06-03 16:11:36.851938 INFO proptest_kafka_input: Test: Specify invalid Kafka broker address
      +test-adapters | 2024-06-03 16:11:46.855244 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855387 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855421 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
      +test-adapters | 2024-06-03 16:11:46.855451 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855480 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855509 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855537 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855565 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855593 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.855620 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:11:46.856164 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic ft_input_test_topic1_input-index: Failed to read metadata for topic ft_input_test_topic1: Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure): BrokerTransportFailure (Local: Broker transport failure)
      +test-adapters | 2024-06-03 16:11:46.861826 INFO proptest_kafka_input: Error: Failed to read index topic ft_input_test_topic1_input-index
      +test-adapters | 2024-06-03 16:11:46.861907 INFO proptest_kafka_input: Test: Specify invalid Kafka topic name
      +test-adapters | 2024-06-03 16:11:46.866937 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic this_topic_does_not_exist_input-index: Error reading metadata for topic this_topic_does_not_exist: Meta data fetch error: UnknownTopicOrPartition (Broker: Unknown topic or partition): UnknownTopicOrPartition (Broker: Unknown topic or partition)
      +test-adapters | 2024-06-03 16:11:46.873574 INFO proptest_kafka_input: Error: Failed to read index topic this_topic_does_not_exist_input-index
      +test-adapters | 2024-06-03 16:11:46.873654 INFO proptest_kafka_input: Building input pipeline
      +test-adapters | 2024-06-03 16:11:46.875757 INFO proptest_kafka_input: Test: Receive from a topic with a single partition
      +test-adapters | 2024-06-03 16:11:46.879789 DEBUG ft_input_test_topic1 has 1 partitions
      +test-adapters | 2024-06-03 16:11:46.880843 INFO Index topic ft_input_test_topic1_input-index does not yet exist, creating with 1 partitions
      +test-adapters | 2024-06-03 16:11:47.878195 DEBUG index topic ft_input_test_topic1_input-index partition 0 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:11:47.882181 DEBUG ft_input_test_topic2 has 2 partitions
      +test-adapters | 2024-06-03 16:11:47.882791 INFO Index topic ft_input_test_topic2_input-index does not yet exist, creating with 2 partitions
      +test-adapters | 2024-06-03 16:11:48.882985 DEBUG index topic ft_input_test_topic2_input-index partition 0 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:11:48.883500 DEBUG index topic ft_input_test_topic2_input-index partition 1 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:11:48.884828 DEBUG creating Kafka producer for index topics
      +test-adapters | 2024-06-03 16:11:48.886332 INFO Kafka non-fatal error: Meta data fetch error: AllBrokersDown (Local: All broker connections are down)
      +test-adapters | 2024-06-03 16:11:49.107678 INFO proptest_kafka_input: Test: Receive from a topic with multiple partitions
      +test-adapters | 2024-06-03 16:11:50.122686 INFO proptest_kafka_input: Test: pause/resume
      +test-adapters | 2024-06-03 16:11:52.460980 INFO proptest_kafka_input: Test: Disconnect
      +test-adapters | 2024-06-03 16:11:55.292123 INFO proptest_kafka_input: Test: Specify invalid Kafka broker address
      +test-adapters | 2024-06-03 16:12:05.295897 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296042 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296078 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
      +test-adapters | 2024-06-03 16:12:05.296107 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296136 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296164 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296192 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296220 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv6#[::1]:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296248 INFO Error FAIL [thrd:localhost:11111/bootstrap]: localhost:11111/bootstrap: Connect to ipv4#127.0.0.1:11111 failed: Connection refused (after 0ms in state CONNECT)
      +test-adapters | 2024-06-03 16:12:05.296936 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic ft_input_test_topic1_input-index: Failed to read metadata for topic ft_input_test_topic1: Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure): BrokerTransportFailure (Local: Broker transport failure)
      +test-adapters | 2024-06-03 16:12:05.304749 INFO proptest_kafka_input: Error: Failed to read index topic ft_input_test_topic1_input-index
      +test-adapters | 2024-06-03 16:12:05.304829 INFO proptest_kafka_input: Test: Specify invalid Kafka topic name
      +test-adapters | 2024-06-03 16:12:05.310175 ERROR Fault-tolerant Kafka input endpoint failed due to: Failed to read index topic this_topic_does_not_exist_input-index: Error reading metadata for topic this_topic_does_not_exist: Meta data fetch error: UnknownTopicOrPartition (Broker: Unknown topic or partition): UnknownTopicOrPartition (Broker: Unknown topic or partition)
      +test-adapters | 2024-06-03 16:12:05.316535 INFO proptest_kafka_input: Error: Failed to read index topic this_topic_does_not_exist_input-index
      +test-adapters | 2024-06-03 16:12:05.316616 INFO proptest_kafka_input: Building input pipeline
      +test-adapters | 2024-06-03 16:12:05.318633 INFO proptest_kafka_input: Test: Receive from a topic with a single partition
      +test-adapters | 2024-06-03 16:12:05.322558 DEBUG ft_input_test_topic1 has 1 partitions
      +test-adapters | 2024-06-03 16:12:05.323456 INFO Index topic ft_input_test_topic1_input-index does not yet exist, creating with 1 partitions
      +test-adapters | 2024-06-03 16:12:06.321282 DEBUG index topic ft_input_test_topic1_input-index partition 0 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:12:06.324704 DEBUG ft_input_test_topic2 has 2 partitions
      +test-adapters | 2024-06-03 16:12:06.325638 INFO Index topic ft_input_test_topic2_input-index does not yet exist, creating with 2 partitions
      +test-adapters | 2024-06-03 16:12:07.325412 DEBUG index topic ft_input_test_topic2_input-index partition 0 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:12:07.325914 DEBUG index topic ft_input_test_topic2_input-index partition 1 has steps 0..0 and watermarks 0..0
      +test-adapters | 2024-06-03 16:12:07.327300 DEBUG creating Kafka producer for index topics
      +test-adapters | 2024-06-03 16:12:07.544512 INFO proptest_kafka_input: Test: Receive from a topic with multiple partitions
      +test-adapters | 2024-06-03 16:12:08.575083 INFO proptest_kafka_input: Test: pause/resume
      +test-adapters | 2024-06-03 16:12:10.897125 INFO proptest_kafka_input: Test: Disconnect
      +test-adapters | proptest: Saving this and future failures in /dbsp/crates/adapters/proptest-regressions/transport/kafka/ft/test.txt
      +test-adapters | proptest: If this test was run on a CI system, you may wish to add the following line to your copy of the file. (You may need to create it.)
      +test-adapters | cc 2ae1ca2bf7d3d2be22d948ae9f6602e3559b2b972b6324f323f193580e0f3ecd
      +test-adapters | thread 'transport::kafka::ft::test::proptest_kafka_input' panicked at crates/adapters/src/transport/kafka/ft/test.rs:767:1:
      +test-adapters | Test failed: called `Result::unwrap()` on an `Err` value: ().
      +test-adapters | minimal failing input: data = [
      +test-adapters |     [
...thousands of lines...
```

Thanks to @snkas for reporting the bug.

**Comment by blp** [comment]
Probably the solution is https://github.com/feldera/dist-design/issues/13

**Comment by blp** [comment]
I think this is fixed.
