### ISSUE TITLE
SQL cast to record type causes SQL exception

### ISSUE THREAD

**Issue by blp** [feldera/feldera#2498]
I tried to compile this SQL program with the Docker container produced with current tip of main at commit 8af71e60127d ("[manager] Improve reporting when the pipeline is dead."):

```
CREATE TABLE t (
   line string
) WITH ('connectors' = '[
    {
        "format": {
            "name": "json",
            "config": {
                "update_format": "raw"
             }
        },
        "transport": {
            "name": "url_input",
            "config": {
                "path": "http://172.17.0.1:9090/log.json"
            }
        }
    }
]');
CREATE TYPE global_metrics AS (
    rss_bytes BIGINT,
    buffered_records BIGINT
);
CREATE LOCAL VIEW tmp AS SELECT PARSE_JSON(line) AS json FROM t;
CREATE VIEW rss AS
       SELECT CAST(json['global_metrics'] AS global_metrics) FROM tmp;
```

I got the following exception:

```
Exception in thread "main" java.lang.RuntimeException: Tup2?<i64?, i64?> is not an instance of class org.dbsp.sqlCompiler.ir.type.primitive.DBSPTypeBaseType
	at org.dbsp.util.ICastable.to(ICastable.java:47)
	at org.dbsp.sqlCompiler.ir.type.DBSPType.baseTypeWithSuffix(DBSPType.java:164)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:758)
	at org.dbsp.sqlCompiler.ir.expression.DBSPCastExpression.accept(DBSPCastExpression.java:56)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:1332)
	at org.dbsp.sqlCompiler.ir.expression.DBSPTupleExpression.accept(DBSPTupleExpression.java:109)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:1137)
	at org.dbsp.sqlCompiler.ir.expression.DBSPClosureExpression.accept(DBSPClosureExpression.java:95)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:823)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.preorder(CircuitVisitor.java:122)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.preorder(CircuitVisitor.java:190)
	at org.dbsp.sqlCompiler.circuit.operator.DBSPMapOperator.accept(DBSPMapOperator.java:51)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.generateOperator(ToRustVisitor.java:351)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.processNode(ToRustVisitor.java:340)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:440)
	at org.dbsp.sqlCompiler.circuit.DBSPPartialCircuit.accept(DBSPPartialCircuit.java:134)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:376)
	at org.dbsp.sqlCompiler.circuit.DBSPCircuit.accept(DBSPCircuit.java:59)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.apply(CircuitVisitor.java:82)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.toRustString(ToRustVisitor.java:1259)
	at org.dbsp.sqlCompiler.compiler.backend.rust.RustFileWriter.write(RustFileWriter.java:400)
	at org.dbsp.sqlCompiler.CompilerMain.run(CompilerMain.java:187)
	at org.dbsp.sqlCompiler.CompilerMain.execute(CompilerMain.java:227)
	at org.dbsp.sqlCompiler.CompilerMain.main(CompilerMain.java:231)
```

I guess this isn't supported but it shouldn't cause the compiler to throw an unhandled exception.

**Comment by mihaibudiu** [comment]
yes, this is not yet implemented

**Comment by mihaibudiu** [comment]
cast to map may have the same fate

**Comment by blp** [comment]
Is this kind of thing the best way to extract multiple fields? I hoped that a single cast to a record type would work.

```
CREATE TABLE t (
   line string
) WITH ('connectors' = '[
    {
        "format": {
            "name": "json",
            "config": {
                "update_format": "raw"
             }
        },
        "transport": {
            "name": "url_input",
            "config": {
                "path": "http://172.17.0.1:9090/log.json"
            }
        }
    }
]');
CREATE LOCAL VIEW tmp AS SELECT PARSE_JSON(line) AS json FROM t;
CREATE LOCAL VIEW gmtmp AS
    SELECT json['global_metrics'] AS global_metrics FROM tmp;
CREATE VIEW global_metrics AS
    SELECT
        CAST(global_metrics['rss_bytes'] AS BIGINT) AS rss,
        CAST(global_metrics['buffered_input_records'] AS BIGINT) AS buffered_input_records,
        CAST(global_metrics['total_input_records'] AS BIGINT) AS total_input_records,
        CAST(global_metrics['total_processed_records'] AS BIGINT) AS total_processed_records,
        CAST(global_metrics['cpu_msecs'] AS BIGINT) AS cpu_msecs
    FROM gmtmp;
```

**Comment by mihaibudiu** [comment]
it will eventually work, but our VARIANT type does not support structs yet, or casts to struct

**Comment by ryzhyk** [comment]
Trouble is, even when this is implemented, it will still panic if the record type doesn't match the structure of the VARIANT. Since VARIANT's can be created from user data, this means that an invalid input can cause a panic.

**Comment by mihaibudiu** [comment]
Casting a variant to any type should always be safe since you can always return null if the type does not match. But we need some rules about what "match" means for structs. At least, all non nullable fields must exist. But what about the other fields? And what about extra fields?

**Comment by ryzhyk** [comment]
> Casting a variant to any type should always be safe since you can always return null if the type does not match

I agree, but I don't think that's how we implemented other casts.

**Comment by mihaibudiu** [comment]
To some degree we did

**Comment by mihaibudiu** [comment]
I will close this issue, since the compiler should report a decent error message in this case.
We have another issue for implementing the feature.
