### ISSUE TITLE
[dbsp] Assertion error for test circuit::dbsp_handle::tests::commit_restore_bounds

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2801]
Test `circuit::dbsp_handle::tests::commit_restore_bounds` failed due to assertion: `cursor.key_valid()`

**Relevant CI run**
https://github.com/feldera/feldera/actions/runs/11442021354
https://github.com/feldera/feldera/actions/runs/11442021354/job/31831445243

**Error snippet**
```
---- circuit::dbsp_handle::tests::commit_restore_bounds stdout ----
thread 'dbsp-worker-0' panicked at crates/dbsp/src/operator/dynamic/sample.rs:313:17:
assertion failed: cursor.key_valid()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:146:5
   3: <dbsp::operator::dynamic::sample::SampleUniqueKeyVals<T> as dbsp::circuit::operator_traits::BinaryOperator<T,usize,dbsp::trace::ord::vec::wset_batch::VecWSet<dyn dbsp::dynamic::pair::Pair<<T as dbsp::trace::BatchReader>::Key,<T as dbsp::trace::BatchReader>::Val>,dyn dbsp::dynamic::weight::WeightTyped+Type = i64>>>::eval
             at ./src/operator/dynamic/sample.rs:313:17
   4: <dbsp::circuit::circuit_builder::BinaryNode<C,I1,I2,O,Op> as dbsp::circuit::circuit_builder::Node>::eval
             at ./src/circuit/circuit_builder.rs:3759:63
   5: <dbsp::circuit::circuit_builder::ChildCircuit<P> as dbsp::circuit::circuit_builder::Circuit>::eval_node
             at ./src/circuit/circuit_builder.rs:2430:18
   6: dbsp::circuit::schedule::dynamic_scheduler::Inner::step
             at ./src/circuit/schedule/dynamic_scheduler.rs:365:21
   7: <dbsp::circuit::schedule::dynamic_scheduler::DynamicScheduler as dbsp::circuit::schedule::Scheduler>::step
             at ./src/circuit/schedule/dynamic_scheduler.rs:401:9
   8: <dbsp::circuit::schedule::OnceExecutor<S> as dbsp::circuit::schedule::Executor<C>>::run
             at ./src/circuit/schedule/mod.rs:190:9
   9: dbsp::circuit::circuit_builder::CircuitHandle::step
             at ./src/circuit/circuit_builder.rs:4636:9
  10: dbsp::circuit::dbsp_handle::<impl dbsp::circuit::runtime::Runtime>::init_circuit::{{closure}}
             at ./src/circuit/dbsp_handle.rs:367:38
  11: dbsp::circuit::runtime::Runtime::run::{{closure}}::{{closure}}
             at ./src/circuit/runtime.rs:410:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'circuit::dbsp_handle::tests::commit_restore_bounds' panicked at crates/dbsp/src/circuit/dbsp_handle.rs:1089:29:
called `Result::unwrap()` on an `Err` value: Runtime(WorkerPanic { panic_info: [(0, WorkerPanicInfo { message: Some("assertion failed: cursor.key_valid()"), location: Some(PanicLocation { file: "crates/dbsp/src/operator/dynamic/sample.rs", line: 313, col: 17 }), backtrace: "   0: dbsp::circuit::runtime::WorkerPanicInfo::new\n             at ./src/circuit/runtime.rs:171:25\n   1: dbsp::circuit::runtime::Runtime::panic\n             at ./src/circuit/runtime.rs:558:26\n   2: dbsp::circuit::runtime::panic_hook::{{closure}}\n             at ./src/circuit/runtime.rs:285:17\n   3: std::thread::local::LocalKey<T>::try_with\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:283:12\n   4: std::thread::local::LocalKey<T>::with\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:260:9\n   5: dbsp::circuit::runtime::panic_hook\n             at ./src/circuit/runtime.rs:282:5\n   6: dbsp::circuit::runtime::Runtime::run::{{closure}}\n             at ./src/circuit/runtime.rs:395:13\n   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2077:9\n   8: std::panicking::rust_panic_with_hook\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:799:13\n   9: std::panicking::begin_panic_handler::{{closure}}\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:656:13\n  10: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:171:18\n  11: rust_begin_unwind\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5\n  12: core::panicking::panic_fmt\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14\n  13: core::panicking::panic\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:146:5\n  14: <dbsp::operator::dynamic::sample::SampleUniqueKeyVals<T> as dbsp::circuit::operator_traits::BinaryOperator<T,usize,dbsp::trace::ord::vec::wset_batch::VecWSet<dyn dbsp::dynamic::pair::Pair<<T as dbsp::trace::BatchReader>::Key,<T as dbsp::trace::BatchReader>::Val>,dyn dbsp::dynamic::weight::WeightTyped+Type = i64>>>::eval\n             at ./src/operator/dynamic/sample.rs:313:17\n  15: <dbsp::circuit::circuit_builder::BinaryNode<C,I1,I2,O,Op> as dbsp::circuit::circuit_builder::Node>::eval\n             at ./src/circuit/circuit_builder.rs:3759:63\n  16: <dbsp::circuit::circuit_builder::ChildCircuit<P> as dbsp::circuit::circuit_builder::Circuit>::eval_node\n             at ./src/circuit/circuit_builder.rs:2430:18\n  17: dbsp::circuit::schedule::dynamic_scheduler::Inner::step\n             at ./src/circuit/schedule/dynamic_scheduler.rs:365:21\n  18: <dbsp::circuit::schedule::dynamic_scheduler::DynamicScheduler as dbsp::circuit::schedule::Scheduler>::step\n             at ./src/circuit/schedule/dynamic_scheduler.rs:401:9\n  19: <dbsp::circuit::schedule::OnceExecutor<S> as dbsp::circuit::schedule::Executor<C>>::run\n             at ./src/circuit/schedule/mod.rs:190:9\n  20: dbsp::circuit::circuit_builder::CircuitHandle::step\n             at ./src/circuit/circuit_builder.rs:4636:9\n  21: dbsp::circuit::dbsp_handle::<impl dbsp::circuit::runtime::Runtime>::init_circuit::{{closure}}\n             at ./src/circuit/dbsp_handle.rs:367:38\n  22: dbsp::circuit::runtime::Runtime::run::{{closure}}::{{closure}}\n             at ./src/circuit/runtime.rs:410:25\n  23: std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:155:18\n  24: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:542:17\n  25: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panic/unwind_safe.rs:272:9\n  26: std::panicking::try::do_call\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40\n  27: __rust_try\n  28: std::panicking::try\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19\n  29: std::panic::catch_unwind\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14\n  30: std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:541:30\n  31: core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5\n  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9\n  33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9\n  34: std::sys::pal::unix::thread::Thread::new::thread_start\n             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys/pal/unix/thread.rs:108:17\n  35: <unknown>\n  36: __clone\n" })] })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1102:23
   4: dbsp::circuit::dbsp_handle::tests::generic_checkpoint_restore
             at ./src/circuit/dbsp_handle.rs:1089:17
   5: dbsp::circuit::dbsp_handle::tests::commit_restore_bounds
             at ./src/circuit/dbsp_handle.rs:1316:9
   6: dbsp::circuit::dbsp_handle::tests::commit_restore_bounds::{{closure}}
             at ./src/circuit/dbsp_handle.rs:1306:31
   7: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    circuit::dbsp_handle::tests::commit_restore_bounds
```

**Comment by blp** [comment]
Does anyone have an idea how to trigger this? I've seen a number of failures in this test in CI (not all the same), but I haven't figured out how to reproduce it locally.

**Comment by blp** [comment]
For example, there was another failure in this test in https://github.com/feldera/feldera/actions/runs/11447586737:

```
---- circuit::dbsp_handle::tests::commit_restore_bounds stdout ----
thread 'circuit::dbsp_handle::tests::commit_restore_bounds' panicked at crates/dbsp/src/circuit/dbsp_handle.rs:1102:13:
assertion `left == right` failed
  left: TypedBatch { inner: VecWSet { layer: {(12, 12): 1, (13, 13): 1} }, phantom: PhantomData<fn(&dbsp::utils::tuple::Tup2<i32, i32>, &(), &i64)> }
 right: TypedBatch { inner: VecWSet { layer: {(9, 10): 1, (12, 12): 1, (13, 13): 1} }, phantom: PhantomData<fn(&dbsp::utils::tuple::Tup2<i32, i32>, &(), &i64)> }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:410:17
   3: core::panicking::assert_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:365:5
   4: dbsp::circuit::dbsp_handle::tests::generic_checkpoint_restore
             at ./src/circuit/dbsp_handle.rs:1102:13
   5: dbsp::circuit::dbsp_handle::tests::commit_restore_bounds
             at ./src/circuit/dbsp_handle.rs:1306:9
   6: dbsp::circuit::dbsp_handle::tests::commit_restore_bounds::{{closure}}
             at ./src/circuit/dbsp_handle.rs:1296:31
   7: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
