### ISSUE TITLE
Demo/hello-world does not work

### ISSUE THREAD

**Issue by ytooyama** [feldera/feldera#2827]
**Describe the bug**
When I run the Demo/hello-world script, an error is displayed and it does not work properly.

**To Reproduce**
- Environment
  - macOS 15
  - Python3.13 (Use Homebrew for installation)
  - pip list
    - certifi            2024.8.30
    - charset-normalizer 3.4.0
    - idna               3.10
    - pip                24.2
    - requests           2.32.3
    - urllib3            2.2.3

- Execution result

```
% docker ps
CONTAINER ID   IMAGE                                     COMMAND                   CREATED       STATUS       PORTS                                                           NAMES
54ad2ad5e63e   ghcr.io/feldera/pipeline-manager:latest   "./pipeline-manager …"   2 hours ago   Up 2 hours   0.0.0.0:8080-8081->8080-8081/tcp, :::8080-8081->8080-8081/tcp   feldera-feldera-1
% curl http://localhost:8080
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" >
    <link rel="icon" href="/favicon.svg" >
    <meta name="viewport" content="width=device-width, initial-scale=1" >

		<link rel="modulepreload" href="/_app/immutable/entry/start.BdWuFox7.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/entry.D9yLpWlh.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/index-client.CZUWBiY4.js">
		<link rel="modulepreload" href="/_app/immutable/entry/app.emGOj3ou.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/preload-helper.DnwsaNae.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/render.bue0joxP.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/utils.ClhGhGR0.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/disclose-version.Bg9kRutz.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/if.BubB1Uwj.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/proxy.Cm34ff3L.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/this.2esU7TeV.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/props.2MRJ04PE.js">
  </head>

  <body data-sveltekit-preload-data="hover" data-theme="feldera-modern-theme" class="h-screen">
    <div class="h-screen preset-tonal-surface">
			<script>
				{
					__sveltekit_174ogra = {
						base: ""
					};

					const element = document.currentScript.parentElement;

					Promise.all([
						import("/_app/immutable/entry/start.BdWuFox7.js"),
						import("/_app/immutable/entry/app.emGOj3ou.js")
					]).then(([kit, app]) => {
						kit.start(app, element);
					});
				}
			</script>
		</div>
  </body>
</html>

% python3 -m venv ./path/to/venv
% source ./path/to/venv/bin/activate

% ls
README.md         matches.csv       path/             requirements.txt
combiner.sql      messages.csv      records.csv       run.py

% python3 run.py --api-url http://localhost:8080
Traceback (most recent call last):
  File "/Users/ytooyama/temp/feldera/feldera/demo/hello-world/run.py", line 143, in <module>
    main()
    ~~~~^^
  File "/Users/ytooyama/temp/feldera/feldera/demo/hello-world/run.py", line 43, in main
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/ytooyama/temp/feldera/feldera/demo/hello-world/path/to/venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8080/v0/programs/demo-hello-world-program
```

**Expected behavior**

It works as described below.
https://github.com/feldera/feldera/tree/main/demo/hello-world

**Screenshots**

```
% python3 run.py --api-url http://localhost:8080
Traceback (most recent call last):
  File "/Users/ytooyama/temp/feldera/feldera/demo/hello-world/run.py", line 143, in <module>
    main()
    ~~~~^^
  File "/Users/ytooyama/temp/feldera/feldera/demo/hello-world/run.py", line 43, in main
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/ytooyama/temp/feldera/feldera/demo/hello-world/path/to/venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8080/v0/programs/demo-hello-world-program
```

**Context (please complete the following information):**
 - Feldera Version: ghcr.io/feldera/pipeline-manager:latest (image id: 4862c140d8f0)
 - Environment: Docker
 - Browser: Firefox
 - Pipeline Configuration/SQL code:
   - https://github.com/feldera/feldera/tree/main/demo/hello-world

**Additional context**

**Comment by ryzhyk** [comment]
Thanks for reporting @ytooyama ! Not all scripts in the `demo` directory are maintained. I am going to remove the `hello-world` one, as it is clearly outdated. If you want to try some simple demos, checkout the pre-packaged examples in the WebConsole (just navigate to localhost:8080 in your browser to see the list).  There is also this [tutorial](https://docs.feldera.com/tutorials/basics/) you can play with.

**Comment by ytooyama** [comment]
Thank you for your reply. I'll try the tutorial right away.
