### ISSUE TITLE
Performance anomalies in nexmark test

### ISSUE THREAD

**Issue by blp** [feldera/feldera#290]
I've been looking at performance today, to be able to report how much of a cost adding distribution support (https://github.com/feldera/dbsp/pull/259) has for strictly single-host workloads. I was seeing some weird stuff, so I switched to main on commit 5df70f898b4c ("Web-based documentation initial import.") and started running some benchmarks.

I found that the following command has weird performance behavior:

```
cargo bench --bench nexmark -- --first-event-rate=10000000 --max-events=100000000 --cpu-cores 6 --num-event-generators 8 --source-buffer-size 10000 --input-batch-size 40000 --query q7
```

This is what I see on my machine:
* The best case for performance is about 15.5 seconds. I get that maybe 25% of the time. In that case, it peaks at about 13.5 GB of RAM as reported in the final summary. The progress bar moves from left to right in a fairly smooth fashion. All the generator and worker threads use roughly 70% of a core, each, during the run.
* In other cases, though, the progress bar visibly stalls at some point for a few seconds. When this happens, the elapsed time ends up being roughly 18 to 27 seconds. The peak RAM use also increases up to as much as 20 GB RAM. Looking at `top`, the generator threads drop to 0% during the stall, and the DBSP worker threads jump up to 100% CPU. After a few seconds, the stall ends and progress resumes.

My current guess is that this is in DBSP and not Nexmark specific.

Back when I was running lots of benchmarks months ago, I did not notice anything like this, so it may be a regression.

**Comment by blp** [comment]
@ryzhyk pointed out that there's already a nexmark performance bug report: https://github.com/feldera/dbsp/issues/38. I think my observations are new information.

**Comment by blp** [comment]
I spent some time digging in and found that the pauses occurred in sorting, with backtraces like the following:

```
#0  core::ptr::mut_ptr::{impl#0}::offset<u8> (count=0, self=<optimized out>) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ptr/mut_ptr.rs:479
#1  core::ptr::mut_ptr::{impl#0}::add<u8> (count=0, self=<optimized out>) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ptr/mut_ptr.rs:1020
#2  core::slice::sort::partition_in_blocks<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), core::slice::{impl#0}::sort_unstable_by::{closure_env#0}<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), dbsp::trace::consolidation::consolidate::{closure_env#0}<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize>>> (v=..., 
    pivot=0x7fe43dc12140, is_less=<optimized out>) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/sort.rs:425
#3  core::slice::sort::partition<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), core::slice::{impl#0}::sort_unstable_by::{closure_env#0}<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), dbsp::trace::consolidation::consolidate::{closure_env#0}<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize>>> (v=..., pivot=..., 
    is_less=<optimized out>) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/sort.rs:598
#4  core::slice::sort::recurse<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), core::slice::{impl#0}::sort_unstable_by::{closure_env#0}<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), dbsp::trace::consolidation::consolidate::{closure_env#0}<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize>>> (v=..., is_less=0x7fe43dc12530, 
    pred=..., limit=24) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/sort.rs:861
#5  0x000055a2f10e2f0f in core::slice::sort::recurse<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), core::slice::{impl#0}::sort_unstable_by::{closure_env#0}<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), dbsp::trace::consolidation::consolidate::{closure_env#0}<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize>>> (v=..., 
    is_less=0x7fe43dc12530, pred=..., limit=24) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/sort.rs:874
#6  0x000055a2f1c3a136 in core::slice::sort::quicksort<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), core::slice::{impl#0}::sort_unstable_by::{closure_env#0}<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), dbsp::trace::consolidation::consolidate::{closure_env#0}<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize>>> (v=..., 
    is_less=...) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/sort.rs:897
#7  core::slice::{impl#0}::sort_unstable_by<((usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize), dbsp::trace::consolidation::consolidate::{closure_env#0}<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize>> (self=..., compare=...) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/mod.rs:2692
#8  dbsp::trace::consolidation::consolidate<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize> (vec=0x7fe43dc12550) at crates/dbsp/src/trace/consolidation/mod.rs:41
#9  dbsp::trace::ord::merge_batcher::MergeSorter<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize>::push<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), isize> (
    batch=..., self=<optimized out>) at crates/dbsp/src/trace/ord/merge_batcher/mod.rs:180
#10 dbsp::trace::ord::merge_batcher::{impl#0}::push_batch<(usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr)), (), isize, dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr), isize, usize>> (self=0x7fe43dc125d0, batch=<optimized out>) at crates/dbsp/src/trace/ord/merge_batcher/mod.rs:45
#11 0x000055a2f195daf6 in dbsp::trace::Batch::from_tuples<dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr), isize, usize>> (
    time=<optimized out>, tuples=<error reading variable: Cannot access memory at address 0x1368a1>) at crates/dbsp/src/trace/mod.rs:307
#12 0x000055a2f1975301 in dbsp::operator::filter_map::{impl#10}::eval<dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<u64, (u64, u64, usize, arcstr::arc_str::ArcStr), isize, usize>, dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr), isize, usize>, dbsp_nexmark::queries::q7::q7::{closure_env#3}> (
    self=<optimized out>, i=<optimized out>) at crates/dbsp/src/operator/filter_map.rs:559
#13 0x000055a2f1243aff in dbsp::circuit::circuit_builder::{impl#31}::eval<dbsp::circuit::circuit_builder::ChildCircuit<()>, dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<u64, (u64, u64, usize, arcstr::arc_str::ArcStr), isize, usize>, dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr), isize, usize>, dbsp::operator::filter_map::Map<dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<u64, (u64, u64, usize, arcstr::arc_str::ArcStr), isize, usize>, dbsp::trace::ord::indexed_zset_batch::OrdIndexedZSet<usize, (u64, u64, usize, u64, arcstr::arc_str::ArcStr), isize, usize>, dbsp_nexmark::queries::q7::q7::{closure_env#3}>> (self=0x39d7a0906e0) at crates/dbsp/src/circuit/circuit_builder.rs:3226
#14 0x000055a2f0f87cfe in dbsp::circuit::circuit_builder::{impl#24}::eval_node<()> (self=<optimized out>, id=...) at crates/dbsp/src/circuit/circuit_builder.rs:2320
#15 0x000055a2f0fd2858 in dbsp::circuit::schedule::dynamic_scheduler::Inner::step<dbsp::circuit::circuit_builder::ChildCircuit<()>> (self=0x39d7a030cc8, circuit=0x7fe43dc12aa0)
    at crates/dbsp/src/circuit/schedule/dynamic_scheduler.rs:372
```

To figure out whether there was anything unusual about the sorting that this talks about, I applied the following patch:

```patch
diff --git a/crates/dbsp/src/trace/ord/merge_batcher/mod.rs b/crates/dbsp/src/trace/ord/merge_batcher/mod.rs
index 94d4b2e1..74f0f0cb 100644
--- a/crates/dbsp/src/trace/ord/merge_batcher/mod.rs
+++ b/crates/dbsp/src/trace/ord/merge_batcher/mod.rs
@@ -177,6 +177,9 @@ impl<D: Ord, R: MonoidValue> MergeSorter<D, R> {
             };
 
             // Consolidate and push the batch we were given
+            if batch.len() > 100000 {
+                println!("{}", batch.len());
+            }
             consolidation::consolidate(&mut batch);
             if !batch.is_empty() {
                 self.queue.push(vec![batch]);
```

When I run the benchmark with this patch and the command line I reported earlier, it prints nothing when the benchmark runs at full speed. When the benchmark pauses, it prints several lines during the pause, such as:

```
8709334
8712401
8709335
8709330
8715465
8709335
8709334
8712401
8709335
8709330
8715465
8709335
8709334
8712401
8709335
8709330
8715465
8709335
```

So, something is nondeterministically causing huge batches that in turn cause processing to pause.

This is where the problem goes deeper than my understanding of the system. @ryzhyk? @Kixiron?

**Comment by blp** [comment]
One run printed the same number many times:

```
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
4066400
```

**Comment by mihaibudiu** [comment]
Can we close this?
