### ISSUE TITLE
occasional CI failure in `circuit::dbsp_handle::tests::gc_commits`

### ISSUE THREAD

**Issue by blp** [feldera/feldera#3100]
Occasionally, CI fails with errors like the following:

```
            +test-dbsp *failed* | ---- circuit::dbsp_handle::tests::gc_commits stdout ----
            +test-dbsp *failed* | thread 'circuit::dbsp_handle::tests::gc_commits' panicked at crates/dbsp/src/circuit/dbsp_handle.rs:1240:13:
            +test-dbsp *failed* | assertion failed: count < prev_count
            +test-dbsp *failed* | stack backtrace:
            +test-dbsp *failed* |    0: rust_begin_unwind
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
            +test-dbsp *failed* |    1: core::panicking::panic_fmt
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
            +test-dbsp *failed* |    2: core::panicking::panic
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:148:5
            +test-dbsp *failed* |    3: dbsp::circuit::dbsp_handle::tests::gc_commits
            +test-dbsp *failed* |              at ./src/circuit/dbsp_handle.rs:1240:13
            +test-dbsp *failed* |    4: dbsp::circuit::dbsp_handle::tests::gc_commits::{{closure}}
            +test-dbsp *failed* |              at ./src/circuit/dbsp_handle.rs:1201:20
            +test-dbsp *failed* |    5: core::ops::function::FnOnce::call_once
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
            +test-dbsp *failed* |    6: core::ops::function::FnOnce::call_once
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
            +test-dbsp *failed* | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  
  
            +test-dbsp *failed* | failures:
            +test-dbsp *failed* |     circuit::dbsp_handle::tests::gc_commits
```

**Comment by snkas** [comment]
Occasional CI failure in `circuit::dbsp_handle::tests::window_checkpointing`

**CI run in which it failed:**
https://github.com/feldera/feldera/actions/runs/12178905664/job/33969898738

**Error snippet:**
```
            +test-dbsp *failed* | ---- circuit::dbsp_handle::tests::window_checkpointing stdout ----
            +test-dbsp *failed* | thread 'dbsp-worker-0' panicked at crates/dbsp/src/storage/backend/io_uring_impl/mod.rs:596:14:
            +test-dbsp *failed* | called `Option::unwrap()` on a `None` value
            +test-dbsp *failed* | stack backtrace:
            +test-dbsp *failed* |    0: rust_begin_unwind
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
            +test-dbsp *failed* |    1: core::panicking::panic_fmt
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
            +test-dbsp *failed* |    2: core::panicking::panic
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:148:5
            +test-dbsp *failed* |    3: core::option::unwrap_failed
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:2015:5
            +test-dbsp *failed* |    4: core::option::Option<T>::unwrap
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:965:21
            +test-dbsp *failed* |    5: <dbsp::storage::backend::io_uring_impl::IoUringBackend as dbsp::storage::backend::Storage>::get_size
            +test-dbsp *failed* |              at ./src/storage/backend/io_uring_impl/mod.rs:591:12
            +test-dbsp *failed* |    6: <alloc::boxed::Box<S> as dbsp::storage::backend::Storage>::get_size
            +test-dbsp *failed* |              at ./src/storage/backend/mod.rs:500:9
            +test-dbsp *failed* |    7: <dbsp::storage::buffer_cache::cache::BufferCache<E> as dbsp::storage::backend::Storage>::get_size
            +test-dbsp *failed* |              at ./src/storage/buffer_cache/cache.rs:367:9
            +test-dbsp *failed* |    8: dbsp::storage::file::reader::Reader<T>::new
            +test-dbsp *failed* |              at ./src/storage/file/reader.rs:1147:25
            +test-dbsp *failed* |    9: dbsp::storage::file::writer::Writer2<K0,A0,K1,A1>::into_reader
            +test-dbsp *failed* |              at ./src/storage/file/writer.rs:1259:9
            +test-dbsp *failed* |   10: <dbsp::trace::ord::file::indexed_wset_batch::FileIndexedWSetBuilder<K,V,R> as dbsp::trace::Builder<dbsp::trace::ord::file::indexed_wset_batch::FileIndexedWSet<K,V,R>>>::done
            +test-dbsp *failed* |              at ./src/trace/ord/file/indexed_wset_batch.rs:945:19
```

**Comment by blp** [comment]
Continuing the backtrace from https://github.com/feldera/feldera/issues/3100#issuecomment-2523676530:

```
            +test-dbsp *failed* |   11: <dbsp::trace::ord::fallback::indexed_wset::FallbackIndexedWSet<K,V,R> as dbsp::trace::Batch>::persisted
            +test-dbsp *failed* |              at ./src/trace/ord/fallback/indexed_wset.rs:390:40
            +test-dbsp *failed* |   12: <dbsp::trace::spine_async::Spine<B> as dbsp::trace::Trace>::commit::persist_batches::{{closure}}
            +test-dbsp *failed* |              at ./src/trace/spine_async/mod.rs:1081:46
            +test-dbsp *failed* |   13: core::iter::adapters::map::map_try_fold::{{closure}}
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/adapters/map.rs:95:28
            +test-dbsp *failed* |   14: <alloc::vec::into_iter::IntoIter<T,A> as core::iter::traits::iterator::Iterator>::try_fold
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/into_iter.rs:346:25
            +test-dbsp *failed* |   15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/adapters/map.rs:121:9
            +test-dbsp *failed* |   16: <I as alloc::vec::in_place_collect::SpecInPlaceCollect<T,I>>::collect_in_place
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/in_place_collect.rs:378:13
            +test-dbsp *failed* |   17: alloc::vec::in_place_collect::from_iter_in_place
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/in_place_collect.rs:269:9
            +test-dbsp *failed* |   18: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/in_place_collect.rs:245:9
            +test-dbsp *failed* |   19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2985:9
            +test-dbsp *failed* |   20: core::iter::traits::iterator::Iterator::collect
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:2000:9
            +test-dbsp *failed* |   21: <dbsp::trace::spine_async::Spine<B> as dbsp::trace::Trace>::commit::persist_batches
            +test-dbsp *failed* |              at ./src/trace/spine_async/mod.rs:1078:13
            +test-dbsp *failed* |   22: <dbsp::trace::spine_async::Spine<B> as dbsp::trace::Trace>::commit
            +test-dbsp *failed* |              at ./src/trace/spine_async/mod.rs:1096:27
            +test-dbsp *failed* |   23: <dbsp::operator::dynamic::trace::Z1Trace<T> as dbsp::circuit::operator_traits::Operator>::commit::{{closure}}
            +test-dbsp *failed* |              at ./src/operator/dynamic/trace.rs:870:26
            +test-dbsp *failed* |   24: core::option::Option<T>::map
            +test-dbsp *failed* |              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:1105:29
            +test-dbsp *failed* |   25: <dbsp::operator::dynamic::trace::Z1Trace<T> as dbsp::circuit::operator_traits::Operator>::commit
            +test-dbsp *failed* |              at ./src/operator/dynamic/trace.rs:868:9
            +test-dbsp *failed* |   26: <dbsp::circuit::circuit_builder::FeedbackOutputNode<C,I,O,Op> as dbsp::circuit::circuit_builder::Node>::commit
            +test-dbsp *failed* |              at ./src/circuit/circuit_builder.rs:4443:18
            +test-dbsp *failed* |   27: dbsp::circuit::circuit_builder::CircuitHandle::commit::{{closure}}
            +test-dbsp *failed* |              at ./src/circuit/circuit_builder.rs:4749:17
            +test-dbsp *failed* |   28: dbsp::circuit::circuit_builder::ChildCircuit<P>::map_nodes_recursive_mut
            +test-dbsp *failed* |              at ./src/circuit/circuit_builder.rs:2324:13
            +test-dbsp *failed* |   29: dbsp::circuit::circuit_builder::CircuitHandle::commit
            +test-dbsp *failed* |              at ./src/circuit/circuit_builder.rs:4746:9
            +test-dbsp *failed* |   30: dbsp::circuit::dbsp_handle::<impl dbsp::circuit::runtime::Runtime>::init_circuit::{{closure}}
            +test-dbsp *failed* |              at ./src/circuit/dbsp_handle.rs:397:25
            +test-dbsp *failed* |   31: dbsp::circuit::runtime::Runtime::run::{{closure}}::{{closure}}
            +test-dbsp *failed* |              at ./src/circuit/runtime.rs:411:25
            +test-dbsp *failed* | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by snkas** [comment]
Re-occurrence: https://github.com/feldera/feldera/actions/runs/12241613178/attempts/2

**Comment by blp** [comment]
I'm working on this.

**Comment by gz** [comment]
havent seen this in a while
