### ISSUE TITLE
yarn cannot generate openapi documentation

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#795]
Not sure whether this is an issue with this repository or with the website, but following the instructions in the website README gives:
```
$ yarn start
yarn run v1.22.19
$ docusaurus start
[INFO] Starting the development server...
Loading of api failed for "/home/mbudiu/git/website/feldera/crates/pipeline_manager/openapi_docs.json"
[ERROR] TypeError: obj must be an Array or an Object
    at /home/mbudiu/git/website/node_modules/json-refs/index.js:799:15
    at async resolveRefs (/home/mbudiu/git/website/node_modules/docusaurus-plugin-openapi/lib/openapi/openapi.js:30:26)
[INFO] Docusaurus version: 2.4.1
Node version: v19.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mihaibudiu** [comment]
Closing this issue, it seems that the problem is a missing jq command.
