### ISSUE TITLE
[JIT] Panic in JIT compiler

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#825]
The actual messages is produced by one change from #824 
Attached are the files that cause the following panic:
```
thread 'main' panicked at '[Some((U8, 8, 0)), None]: checking nullability of non-nullable column 1', crates/dataflow-jit/src/codegen/layout.rs:440:12
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: dataflow_jit::codegen::layout::NativeLayout::nullability_of::{{closure}}
             at ./crates/dataflow-jit/src/codegen/layout.rs:440:9
   3: core::option::Option<T>::unwrap_or_else
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/option.rs:979:21
   4: dataflow_jit::codegen::layout::NativeLayout::nullability_of
             at ./crates/dataflow-jit/src/codegen/layout.rs:439:9
   5: dataflow_jit::codegen::CodegenCtx::set_null
             at ./crates/dataflow-jit/src/codegen/mod.rs:1416:51
   6: dataflow_jit::codegen::Codegen::codegen_func
             at ./crates/dataflow-jit/src/codegen/mod.rs:397:52
   7: dataflow_jit::dataflow::collect_functions
             at ./crates/dataflow-jit/src/dataflow/mod.rs:1585:21
   8: dataflow_jit::dataflow::CompiledDataflow::new
             at ./crates/dataflow-jit/src/dataflow/mod.rs:171:9
   9: dataflow_jit::facade::DbspCircuit::new
             at ./crates/dataflow-jit/src/facade/mod.rs:114:45
  10: dataflow_jit::run
             at ./crates/dataflow-jit/src/main.rs:151:23
  11: dataflow_jit::main
             at ./crates/dataflow-jit/src/main.rs:37:42
  12: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
```
I poked around, but the `set_null` that is invoked does not seem to be present in the original program, all the `set_null`s use column 0, while this is an error for column 1.

**Comment by mihaibudiu** [comment]
[bug.zip](https://github.com/feldera/feldera/files/12785572/bug.zip)

**Comment by Kixiron** [comment]
Please minimize programs before reporting bugs, this is too large for me to reasonably approach

**Comment by mihaibudiu** [comment]
This is a one-line query, I am not sure it can be made smaller.
`SELECT DISTINCT -98 * AVG(79) + + COUNT(*) * COUNT(*) AS COL0 FROM TAB2 AS COR0 WHERE + COL1 IS NULL`

**Comment by Kixiron** [comment]
Minimize the program itself, not the source sql

**Comment by mihaibudiu** [comment]
I don't have any way of doing that.

**Comment by Kixiron** [comment]
You can edit the produced json

**Comment by mihaibudiu** [comment]
I don't plan to work on minimizing this bug in the next two weeks. In general assertion failures in the compiler should be manageable bugs.

**Comment by Kixiron** [comment]
Something's wrong on your side, the expression in question is
```json
[
    20,
    {
        "SetNull": {
            "target": 2,
            "target_layout": 5,
            "column": 1,
            "is_null": {
                "Expr": 16
            }
        }
    }
]
```
where layout 5 is
```json
"5": {
    "columns": [
        {
            "nullable": true,
            "ty": "I32"
        },
        {
            "nullable": false,
            "ty": "I64"
        }
    ]
},
```
and column 1 isn't nullable, so the behavior here is to be expected
