### ISSUE TITLE
Polish the Python API

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#88]
The API is currently very crude, especially when it comes to error reporting. It also doesn't expose all of the REST API. We need to take a pass over it before 0.1 release.

- [ ] Decide on the overall design of the API, e.g., 1-1 mappings for the REST API vs higher-level abstractions.
- [ ] Add bindings for HTTP ingress/egress.
  - [ ] Use these bindings in the fraud detection demo; make sure the demo runs inside docker.
- [ ] Make sure errors propagate to the client (see @gz's example below)
- [ ] Implement missing bindings (currently only a subset of the API is covered by bindings)
- [ ] Generate API documentation, publish it in docs

**Comment by gz** [comment]
I got this error and it was hard to figure out what went wrong without looking at the pipeline manager log seems like there is some issue with getting the error back to the caller when there is a 500 error?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 3
      1 run_query(train_path, train_outpath)
      2 print("Training pipeline finished")
----> 3 run_query(test_path, test_outpath)
      4 print("Test pipeline finished")

Cell In[4], line 10, in run_query(transaction_file, output_file)
      7 config.add_file_input(stream = 'TRANSACTIONS', filepath = transaction_file, format = CsvInputFormatConfig())
      8 config.add_file_output(stream = 'FEATURES', filepath = output_file, format = CsvOutputFormatConfig())
---> 10 config.run_to_completion()

File ~/workspace/dbsp/python/dbsp/pipeline.py:273, in DBSPPipelineConfig.run_to_completion(self, timeout)
    263 def run_to_completion(self, timeout: float = sys.maxsize):
    264     """Launch a new pipeline, wait for it to run to completion, and delete the pipeline.
    265 
    266     This method should only be used for pipelines configured with finite input streams, e.g., files.
   (...)
    271         dbsp.TimeoutException: If the pipeline does not terminate within 'timeout' seconds.
    272     """
--> 273     self.run()
    274     try:
    275         self.wait(timeout)

File ~/workspace/dbsp/python/dbsp/pipeline.py:214, in DBSPPipelineConfig.run(self)
    205 """Launch a new pipeline.
    206 
    207 Create and run a new pipeline for the specified configuration.
   (...)
    211     dbsp.DBSPServerError: If the DBSP server returns an error.
    212 """
    213 self.save()
--> 214 pipeline_action.sync_detailed(
    215     client=self.api_client, pipeline_id=self.pipeline_id, action='deploy').unwrap("Failed to deploy pipeline")
    216 self.status = PipelineStatus.DEPLOYED
    217 pipeline_action.sync_detailed(
    218     client=self.api_client, pipeline_id=self.pipeline_id, action='start').unwrap("Failed to start pipeline")

File ~/workspace/dbsp/python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_action.py:111, in sync_detailed(pipeline_id, action, client)
    100 kwargs = _get_kwargs(
    101     pipeline_id=pipeline_id,
    102     action=action,
    103     client=client,
    104 )
    106 response = httpx.request(
    107     verify=client.verify_ssl,
    108     **kwargs,
    109 )
--> 111 return _build_response(client=client, response=response)

File ~/workspace/dbsp/python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_action.py:64, in _build_response(client, response)
     59 def _build_response(*, client: Client, response: httpx.Response) -> Response[Union[ErrorResponse, str]]:
     60     return Response(
     61         status_code=HTTPStatus(response.status_code),
     62         content=response.content,
     63         headers=response.headers,
---> 64         parsed=_parse_response(client=client, response=response),
     65     )

File ~/workspace/dbsp/python/dbsp-api-client/dbsp_api_client/api/pipeline/pipeline_action.py:46, in _parse_response(client, response)
     44     return response_404
     45 if response.status_code == HTTPStatus.INTERNAL_SERVER_ERROR:
---> 46     response_500 = ErrorResponse.from_dict(response.json())
     48     return response_500
     49 if response.status_code == HTTPStatus.SERVICE_UNAVAILABLE:

File ~/workspace/dbsp/python/dbsp-api-client/dbsp_api_client/models/error_response.py:51, in ErrorResponse.from_dict(cls, src_dict)
     48 from ..models.error_response_details import ErrorResponseDetails
     50 d = src_dict.copy()
---> 51 details = ErrorResponseDetails.from_dict(d.pop("details"))
     53 error_code = d.pop("error_code")
     55 message = d.pop("message")

File ~/workspace/dbsp/python/dbsp-api-client/dbsp_api_client/models/error_response_details.py:26, in ErrorResponseDetails.from_dict(cls, src_dict)
     24 @classmethod
     25 def from_dict(cls: Type[T], src_dict: Dict[str, Any]) -> T:
---> 26     d = src_dict.copy()
     27     error_response_details = cls()
     29     error_response_details.additional_properties = d

AttributeError: 'NoneType' object has no attribute 'copy'
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by gz** [comment]
I ran into a problem with the python api.. I'm not sure about the exact cause but I had in my setup previously created the connectors for the secops demo manually (using same name but different host/topic etc.) then I tried to run the secops python script to re-create it and it failed with an exception:


```
python3 run.py --dbsp_url http://localhost:8080
Traceback (most recent call last):
  File "/home/gz/workspace/dbsp/demo/project_demo00-SecOps/run.py", line 95, in <module>
    run_demo(
  File "/home/gz/workspace/dbsp/demo/../demo/__init__.py", line 57, in run_demo
    execute(dbsp_url, actions, name, code_file,
  File "/home/gz/workspace/dbsp/demo/../demo/__init__.py", line 11, in execute
    pipeline = make_pipeline_fn(program)
  File "/home/gz/workspace/dbsp/demo/project_demo00-SecOps/run.py", line 42, in make_config
    config.add_kafka_input(
  File "/home/gz/workspace/dbsp/python/dbsp/pipeline.py", line 80, in add_kafka_input
    DBSPConnector(self.api_client, name, TransportConfig(
  File "/home/gz/workspace/dbsp/python/dbsp/connector.py", line 35, in __init__
    response = list_connectors.sync_detailed(
  File "/home/gz/.local/lib/python3.10/site-packages/dbsp_api_client/api/connectors/list_connectors.py", line 98, in sync_detailed
    return _build_response(client=client, response=response)
  File "/home/gz/.local/lib/python3.10/site-packages/dbsp_api_client/api/connectors/list_connectors.py", line 63, in _build_response
    parsed=_parse_response(client=client, response=response),
  File "/home/gz/.local/lib/python3.10/site-packages/dbsp_api_client/api/connectors/list_connectors.py", line 41, in _parse_response
    response_200_item = ConnectorDescr.from_dict(response_200_item_data)
  File "/home/gz/.local/lib/python3.10/site-packages/dbsp_api_client/models/connector_descr.py", line 54, in from_dict
    config = ConnectorConfig.from_dict(d.pop("config"))
  File "/home/gz/.local/lib/python3.10/site-packages/dbsp_api_client/models/connector_config.py", line 65, in from_dict
    format_ = FormatConfig.from_dict(d.pop("format"))
  File "/home/gz/.local/lib/python3.10/site-packages/dbsp_api_client/models/format_config.py", line 58, in from_dict
    config = FormatConfigConfig.from_dict(_config)
  File "/home/gz/.local/lib/python3.10/site-packages/dbsp_api_client/models/format_config_config.py", line 23, in from_dict
    d = src_dict.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

after deleting the connectors, I was able to run the script successfully

**Comment by lalithsuresh** [comment]
@gz this this because of the create_or_replace() workflows now being broken due to the API polishing PR. Deleting a program no longer deletes the pipeline. This therefore requires the caller to first shutdown the pipeline, then wait until the shutdown actually happens by probing /pipelines/{pipeline_id} and checking the status field, then deleting the pipeline followed by the program.

**Comment by gz** [comment]
Shouldn't it have just updated the connectors with the new content since they already existed with this name? That's what my expectation was -- fwiw the pipeline wasn't running (in fact the pipeline the script would've to create didn't exist yet, just the connectors were there)

In any case the error seems strange at it fails somewhere deep in the generated code rather than throwing something that a user would understand.

**Comment by ryzhyk** [comment]
This is a combination of two issues: (1) error reporting doesn't work in the Python API, (2) we don't have a single endpoint with create-or-update semantics for connectors (or any other objects at this point). Both will be addressed as part of this issues.  For (2) in particular the plan is to create higher-level APIs on top of the primitive REST endpoints.

**Comment by gz** [comment]
Btw. I forgot to mention it is a regression as this used to work a few days ago (running the script twice with connectors already pre-existing). I do think the python API has logic to handle this case alredy (if you get a name exist error) it'll try to update. But looks like something broke this.

**Comment by ryzhyk** [comment]
Nope. We have an API to modify an existing connector and an API to create a new one.  The demo uses the latter, which fails if a connector with this name exists. There is no way to create a connector or update an existing one with a single API call.

**Comment by ryzhyk** [comment]
Ok, I seem, maybe there's something else going on then.

**Comment by ryzhyk** [comment]
Closing.  The API is on its way out.
